TRUNCATE TABLE Fact_Streams_SSIS;
TRUNCATE TABLE Bridge_Track_Artist_SSIS;

TRUNCATE TABLE Dim_Track_SSIS;
TRUNCATE TABLE Dim_Artist_SSIS;
TRUNCATE TABLE Dim_Album_SSIS;
TRUNCATE TABLE Dim_Sound_SSIS;
TRUNCATE TABLE Dim_Time_SSIS;