In [2]:
import math
import numpy as np
import pandas as pd

In [22]:
crashes = pd.read_csv('C:/Users/al797/Desktop/Crashes.csv') C:\Users\al797\Documents\GitHub\LDS-project-24-25\CSV

In [10]:
merged = pd.read_csv('C:/Users/al797/Documenti/GitHub/LDS-Project-24-25/CSV/merged.csv')

In [80]:
crash = pd.read_csv('C:/Users/al797/Documenti/GitHub/LDS-Project-24-25/CSV/Crashes_filled.csv')

In [18]:
date = pd.read_csv('C:/Users/al797/Documenti/GitHub/LDS-Project-24-25/CSV/Crash_date.csv')

In [61]:
people = pd.read_csv('C:/Users/al797/Documenti/GitHub/LDS-Project-24-25/CSV/People_filled.csv')

In [82]:
veh = pd.read_csv('C:/Users/al797/Documenti/GitHub/LDS-Project-24-25/CSV/Vehicles_filled.csv')

In [19]:
damage = pd.read_csv('C:/Users/al797/Documenti/GitHub/LDS-Project-24-25/CSV/damage.csv')

In [39]:
person = pd.read_csv('C:/Users/al797/Documenti/GitHub/LDS-Project-24-25/CSV/Person.csv')

In [66]:
damage = pd.read_csv('C:/Users/al797/Documenti/GitHub/LDS-Project-24-25/CSV/Damage.csv')

In [22]:
crashes = pd.read_csv('C:/Users/al797/Desktop/Crashes.csv')

In [29]:
person[person.duplicated()]

Empty DataFrame
Columns: [PERSON_ID, PERSON_TYPE, SEX, AGE, SAFETY_EQUIPMENT, INJURY_CLASSIFICATION, DAMAGE_CATEGORY, CITY, STATE]
Index: []

In [31]:
pp = person[['PERSON_ID', 'PERSON_TYPE', 'SEX', 'AGE', 'SAFETY_EQUIPMENT', 'INJURY_CLASSIFICATION', 'CITY', 'STATE']]

In [34]:
# Filtrare le righe con person_id duplicati
duplicated_person_ids = person[person['PERSON_ID'].duplicated(keep=False)]
duplicated_person_ids

Empty DataFrame
Columns: [PERSON_ID, PERSON_TYPE, SEX, AGE, SAFETY_EQUIPMENT, INJURY_CLASSIFICATION, DAMAGE_CATEGORY, CITY, STATE]
Index: []

In [65]:
aaa = merged[merged['PERSON_ID'] == 'O519009']
aaa[['PERSON_ID', 'DAMAGE', 'RD_NO', 'CRASH_UNIT_ID', 'VEHICLE_ID', 'PERSON_TYPE', 'VEHICLE_TYPE']]

PERSON_ID   DAMAGE     RD_NO  CRASH_UNIT_ID  VEHICLE_ID PERSON_TYPE  \
41357   O519009  3533.50  JB510484         519006    495751.0  PEDESTRIAN   
41358   O519009  6639.49  JB510484         519006    495751.0  PEDESTRIAN   
41359   O519009  4176.56  JB510484         519006    495751.0  PEDESTRIAN   
41360   O519009  3652.49  JB510484         519006    495751.0  PEDESTRIAN   

      VEHICLE_TYPE  
41357    PASSENGER  
41358    PASSENGER  
41359    PASSENGER  
41360    PASSENGER

In [55]:
veh[veh['CRASH_UNIT_ID'] == 519006]

CRASH_UNIT_ID  VEHICLE_ID UNIT_TYPE  UNIT_NO        MAKE MODEL  \
18787         519006    495751.0    PARKED        2  VOLKSWAGEN    CC   

       VEHICLE_YEAR VEHICLE_DEFECT VEHICLE_USE  OCCUPANT_CNT VEHICLE_TYPE  
18787        2011.0        UNKNOWN    PERSONAL           1.0    PASSENGER

In [86]:
ax = merged['PERSON_ID'].duplicated().sum()

ax

324

In [74]:
import pandas as pd

def find_duplicates(file):
    # Carica il file CSV in un DataFrame
    df = pd.read_csv(file, encoding='utf-8')
    
    # Identifica le righe duplicate basandoti su PERSON_ID e CRASH_UNIT_ID
    duplicate_rows = df[df.duplicated(subset=['PERSON_ID', 'CRASH_UNIT_ID'], keep=False)]
    
    return duplicate_rows  # Restituisci le righe duplicate come DataFrame

# Esempio di utilizzo
duplicates_df = find_duplicates('C:/Users/al797/Documenti/GitHub/LDS-Project-24-25/CSV/merged.csv')

# Stampa il DataFrame con i duplicati (opzionale)
duplicates_df


PERSON_ID PERSON_TYPE     RD_NO  VEHICLE_ID              CRASH_DATE  \
1649     O559393  PEDESTRIAN  JC108902        -1.0  01/08/2019 08:30:00 AM   
1650     O559393  PEDESTRIAN  JC108902        -1.0  01/08/2019 08:30:00 AM   
1651     O559394  PEDESTRIAN  JC108902        -1.0  01/08/2019 08:30:00 AM   
1652     O559394  PEDESTRIAN  JC108902        -1.0  01/08/2019 08:30:00 AM   
1965     O558992  PEDESTRIAN  JC108139        -1.0  01/07/2019 03:15:00 PM   
...          ...         ...       ...         ...                     ...   
546976    O17742     BICYCLE  HY535803        -1.0  12/12/2015 03:30:00 AM   
562113     O2353  PEDESTRIAN  HY427241        -1.0  09/17/2015 04:26:00 PM   
562114     O2353  PEDESTRIAN  HY427241        -1.0  09/17/2015 04:26:00 PM   
562115     O2369  PEDESTRIAN  HY427241        -1.0  09/17/2015 04:26:00 PM   
562116     O2369  PEDESTRIAN  HY427241        -1.0  09/17/2015 04:26:00 PM   

                  CITY STATE SEX   AGE SAFETY_EQUIPMENT  ...  \
1649           CHICAGO    IL   U  11.0     NONE PRESENT  ...   
1650           CHICAGO    IL   U  11.0     NONE PRESENT  ...   
1651           CHICAGO    IL   F  36.0     NONE PRESENT  ...   
1652           CHICAGO    IL   F  36.0     NONE PRESENT  ...   
1965           CHICAGO    IL   F  10.0     NONE PRESENT  ...   
...                ...   ...  ..   ...              ...  ...   
546976         CHICAGO    IL   M  25.0      HELMET USED  ...   
562113  EVERGREEN PARK    IL   F   8.0    USAGE UNKNOWN  ...   
562114  EVERGREEN PARK    IL   F   8.0    USAGE UNKNOWN  ...   
562115  EVERGREEN PARK    IL   F  10.0     NONE PRESENT  ...   
562116  EVERGREEN PARK    IL   F  10.0     NONE PRESENT  ...   

       INJURIES_NON_INCAPACITATING INJURIES_REPORTED_NOT_EVIDENT  \
1649                           0.0                           0.0   
1650                           0.0                           0.0   
1651                           0.0                           0.0   
1652                           0.0                           0.0   
1965                           2.0                           0.0   
...                            ...                           ...   
546976                         1.0                           0.0   
562113                         1.0                           0.0   
562114                         1.0                           0.0   
562115                         1.0                           0.0   
562116                         1.0                           0.0   

       INJURIES_NO_INDICATION INJURIES_UNKNOWN CRASH_HOUR CRASH_DAY_OF_WEEK  \
1649                      1.0              0.0          8                 3   
1650                      1.0              0.0          8                 3   
1651                      1.0              0.0          8                 3   
1652                      1.0              0.0          8                 3   
1965                      2.0              0.0         15                 2   
...                       ...              ...        ...               ...   
546976                    2.0              0.0          3                 7   
562113                    1.0              0.0         16                 5   
562114                    1.0              0.0         16                 5   
562115                    1.0              0.0         16                 5   
562116                    1.0              0.0         16                 5   

       CRASH_MONTH   LATITUDE  LONGITUDE  \
1649             1  41.902443 -87.733804   
1650             1  41.902443 -87.733804   
1651             1  41.902443 -87.733804   
1652             1  41.902443 -87.733804   
1965             1  41.876536 -87.700937   
...            ...        ...        ...   
546976          12  41.909007 -87.707131   
562113           9  41.766191 -87.564770   
562114           9  41.766191 -87.564770   
562115           9  41.766191 -87.564770   
562116           9  41.766191 -87.564770   

      

In [76]:
print(crash.duplicated('LOCATION').sum())
print(person.duplicated('PRIM_CONTRIBUTORY_CAUSE').sum())
print(veh.duplicated('RD_NO').sum())


KeyError: Index(['LOCATION'], dtype='object')

In [75]:
import pandas as pd

# Carica il dataset
file_path = 'C:/Users/al797/Documenti/GitHub/LDS-Project-24-25/CSV/merged.csv'
df = pd.read_csv(file_path, encoding='utf-8')

# Trova duplicati basati su colonne chiave
duplicate_columns = ['PERSON_ID', 'RD_NO', 'CRASH_DATE', 'LATITUDE', 'LONGITUDE']
duplicates_df = df[df.duplicated(subset=duplicate_columns, keep=False)]

# Stampa i risultati
print(f"Righe duplicate trovate: {len(duplicates_df)}")
print(duplicates_df)

# Se vuoi, salva i duplicati in un file CSV
output_path = 'duplicati_output.csv'
duplicates_df.to_csv(output_path, index=False)
print(f"File duplicati salvato in: {output_path}")


Righe duplicate trovate: 599
       PERSON_ID PERSON_TYPE     RD_NO  VEHICLE_ID              CRASH_DATE  \
1649     O559393  PEDESTRIAN  JC108902        -1.0  01/08/2019 08:30:00 AM   
1650     O559393  PEDESTRIAN  JC108902        -1.0  01/08/2019 08:30:00 AM   
1651     O559394  PEDESTRIAN  JC108902        -1.0  01/08/2019 08:30:00 AM   
1652     O559394  PEDESTRIAN  JC108902        -1.0  01/08/2019 08:30:00 AM   
1965     O558992  PEDESTRIAN  JC108139        -1.0  01/07/2019 03:15:00 PM   
...          ...         ...       ...         ...                     ...   
546976    O17742     BICYCLE  HY535803        -1.0  12/12/2015 03:30:00 AM   
562113     O2353  PEDESTRIAN  HY427241        -1.0  09/17/2015 04:26:00 PM   
562114     O2353  PEDESTRIAN  HY427241        -1.0  09/17/2015 04:26:00 PM   
562115     O2369  PEDESTRIAN  HY427241        -1.0  09/17/2015 04:26:00 PM   
562116     O2369  PEDESTRIAN  HY427241        -1.0  09/17/2015 04:26:00 PM   

                  CITY STATE SEX  

In [3]:
people = pd.read_csv('C:/Users/al797/Desktop/People.csv')

In [4]:
vehicles = pd.read_csv('C:/Users/al797/Desktop/Vehicles.csv')

In [23]:
crashes[crashes['RD_NO'] == 'JB289954']

RD_NO              CRASH_DATE  POSTED_SPEED_LIMIT  \
72486  JB289954  06/01/2018 06:00:00 AM                  30   

      TRAFFIC_CONTROL_DEVICE DEVICE_CONDITION WEATHER_CONDITION  \
72486                UNKNOWN          UNKNOWN           UNKNOWN   

      LIGHTING_CONDITION FIRST_CRASH_TYPE TRAFFICWAY_TYPE           ALIGNMENT  \
72486            UNKNOWN         REAR END         UNKNOWN  STRAIGHT AND LEVEL   

       ... INJURIES_NON_INCAPACITATING INJURIES_REPORTED_NOT_EVIDENT  \
72486  ...                         0.0                           0.0   

      INJURIES_NO_INDICATION INJURIES_UNKNOWN CRASH_HOUR CRASH_DAY_OF_WEEK  \
72486                    3.0              0.0          6                 6   

      CRASH_MONTH  LATITUDE LONGITUDE LOCATION  
72486           6       NaN       NaN      NaN  

[1 rows x 36 columns]

In [24]:
crashes['CRASH_DATE'].value_counts()

CRASH_DATE
11/10/2017 10:30:00 AM    27
11/10/2017 10:00:00 AM    20
09/04/2018 08:00:00 AM    16
01/25/2018 08:00:00 AM    15
10/10/2018 03:30:00 PM    15
                          ..
02/15/2018 04:32:00 PM     1
02/15/2018 04:40:00 PM     1
02/15/2018 04:50:00 PM     1
02/15/2018 05:03:00 PM     1
01/18/2014 06:14:00 PM     1
Name: count, Length: 166465, dtype: int64

In [16]:
crashes.dtype

AttributeError: 'DataFrame' object has no attribute 'dtype'

In [5]:
crashes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 257925 entries, 0 to 257924
Data columns (total 36 columns):
 #   Column                         Non-Null Count   Dtype  
---  ------                         --------------   -----  
 0   RD_NO                          257925 non-null  object 
 1   CRASH_DATE                     257925 non-null  object 
 2   POSTED_SPEED_LIMIT             257925 non-null  int64  
 3   TRAFFIC_CONTROL_DEVICE         257925 non-null  object 
 4   DEVICE_CONDITION               257925 non-null  object 
 5   WEATHER_CONDITION              257925 non-null  object 
 6   LIGHTING_CONDITION             257925 non-null  object 
 7   FIRST_CRASH_TYPE               257925 non-null  object 
 8   TRAFFICWAY_TYPE                257925 non-null  object 
 9   ALIGNMENT                      257925 non-null  object 
 10  ROADWAY_SURFACE_COND           257925 non-null  object 
 11  ROAD_DEFECT                    257925 non-null  object 
 12  REPORT_TYPE                   

In [17]:
crashes['CRASH_DATE']

0         01/12/2019 12:01:00 AM
1         01/11/2019 11:36:00 PM
2         01/11/2019 11:31:00 PM
3         01/11/2019 11:22:00 PM
4         01/11/2019 11:08:00 PM
                   ...          
257920    11/11/2014 08:00:00 PM
257921    08/20/2014 04:50:00 PM
257922    02/24/2014 07:45:00 PM
257923    01/21/2014 07:40:00 AM
257924    01/18/2014 06:14:00 PM
Name: CRASH_DATE, Length: 257925, dtype: object

In [9]:
cols = vehicles.columns
for col in cols:
    print(vehicles[col].value_counts())

CRASH_UNIT_ID
561555    1
180234    1
180167    1
180166    1
180165    1
         ..
368914    1
368894    1
368863    1
368862    1
481322    1
Name: count, Length: 460437, dtype: int64
RD_NO
JA522872    10
JA518406     8
JB210669     8
JB174902     8
JB571997     8
            ..
JA510569     1
JA510617     1
JA510678     1
JA510735     1
JA537431     1
Name: count, Length: 257925, dtype: int64
CRASH_DATE
11/10/2017 10:30:00 AM    51
11/10/2017 10:00:00 AM    39
04/04/2018 07:30:00 AM    29
09/04/2018 08:00:00 AM    29
06/01/2018 04:00:00 PM    28
                          ..
12/28/2016 04:35:00 PM     1
12/28/2016 03:40:00 PM     1
12/28/2016 03:14:00 PM     1
12/28/2016 03:13:00 PM     1
01/12/2019 12:01:00 AM     1
Name: count, Length: 166465, dtype: int64
UNIT_NO
1     256950
2     193611
3       8675
4        964
5        168
6         38
7         13
8          7
0          6
9          3
10         2
Name: count, dtype: int64
UNIT_TYPE
DRIVER                 444982
PEDESTRIAN

In [50]:
crashes['REPORT_TYPE'].value_counts()

REPORT_TYPE
NOT ON SCENE (DESK REPORT)    167961
ON SCENE                       84968
Name: count, dtype: int64

In [26]:
people.columns

Index(['PERSON_ID', 'PERSON_TYPE', 'RD_NO', 'VEHICLE_ID', 'CRASH_DATE', 'CITY',
       'STATE', 'SEX', 'AGE', 'SAFETY_EQUIPMENT', 'AIRBAG_DEPLOYED',
       'EJECTION', 'INJURY_CLASSIFICATION', 'DRIVER_ACTION', 'DRIVER_VISION',
       'PHYSICAL_CONDITION', 'BAC_RESULT', 'DAMAGE_CATEGORY', 'DAMAGE'],
      dtype='object')

In [30]:
ab = vehicles[vehicles['OCCUPANT_CNT'].isnull()]
ab['UNIT_TYPE']

56        PEDESTRIAN
87           BICYCLE
100       PEDESTRIAN
147       PEDESTRIAN
381       PEDESTRIAN
             ...    
460042       BICYCLE
460064       BICYCLE
460088       BICYCLE
460168    PEDESTRIAN
460262    PEDESTRIAN
Name: UNIT_TYPE, Length: 10373, dtype: object

In [7]:
crashes['ROADWAY_SURFACE_COND'].value_counts()

ROADWAY_SURFACE_COND
DRY                195116
WET                 35351
UNKNOWN             17018
SNOW OR SLUSH        7893
ICE                  1785
OTHER                 626
SAND, MUD, DIRT       136
Name: count, dtype: int64

In [10]:
crashes['INJURIES_FATAL']

0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
         ... 
257920    0.0
257921    0.0
257922    0.0
257923    0.0
257924    0.0
Name: INJURIES_FATAL, Length: 257925, dtype: float64

## CRASHES MISSING VALUES

In [36]:
filtered_vehicles = vehicles[vehicles['VEHICLE_YEAR'] > 2024]

filtered_vehicles['VEHICLE_YEAR'].unique()

array([2103., 9999., 2204., 2915., 2913., 2205., 3007., 2107., 2041.,
       2999., 2917., 2105., 2201., 2104., 2918., 2911., 2916., 2099.,
       2208., 3017., 2033., 2207., 2028., 2096., 2206., 2102., 2055.,
       2108., 3013., 5007., 3003., 2106., 2202., 2027., 2088., 2998.,
       3016., 3023., 2040., 2114., 2994., 2203., 2914., 2402., 2100.,
       2912., 2101., 2045., 5015., 2910., 2222., 2113., 2112., 2992.,
       3004., 5555., 2110., 5012., 3012., 2117., 6043.])

In [28]:
filtered_vehicles['VEHICLE_YEAR'].count





()

422

In [5]:
crashes.columns

Index(['RD_NO', 'CRASH_DATE', 'POSTED_SPEED_LIMIT', 'TRAFFIC_CONTROL_DEVICE',
       'DEVICE_CONDITION', 'WEATHER_CONDITION', 'LIGHTING_CONDITION',
       'FIRST_CRASH_TYPE', 'TRAFFICWAY_TYPE', 'ALIGNMENT',
       'ROADWAY_SURFACE_COND', 'ROAD_DEFECT', 'REPORT_TYPE', 'CRASH_TYPE',
       'DATE_POLICE_NOTIFIED', 'PRIM_CONTRIBUTORY_CAUSE',
       'SEC_CONTRIBUTORY_CAUSE', 'STREET_NO', 'STREET_DIRECTION',
       'STREET_NAME', 'BEAT_OF_OCCURRENCE', 'NUM_UNITS', 'MOST_SEVERE_INJURY',
       'INJURIES_TOTAL', 'INJURIES_FATAL', 'INJURIES_INCAPACITATING',
       'INJURIES_NON_INCAPACITATING', 'INJURIES_REPORTED_NOT_EVIDENT',
       'INJURIES_NO_INDICATION', 'INJURIES_UNKNOWN', 'CRASH_HOUR',
       'CRASH_DAY_OF_WEEK', 'CRASH_MONTH', 'LATITUDE', 'LONGITUDE',
       'LOCATION'],
      dtype='object')

Missing values:

REPORT_TYPE                      4996 X quelli con morti o feriti gravi vanno ON SCENE (circa 500), gli altri NOS

STREET_DIRECTION                    2  X quelle due strade hanno solo una direzione quindi top

STREET_NAME                         1  X NON ABBIAMO MODO DI TROVARLO, SI ELIMINA

BEAT_OF_OCCURRENCE                  4  X moda per le righe che hanno la stessa strada

MOST_SEVERE_INJURY                  7   X tutti 0 perche non si sono fatti nulla

LATITUDE                         1022   ? usare il coso di napo

LONGITUDE                        1022   ? usare il coso di napo

LOCATION                         1022   ? di conseguenza dopo longitude e latitude


In [13]:
crashes

RD_NO              CRASH_DATE  POSTED_SPEED_LIMIT  \
0       JC113649  01/12/2019 12:01:00 AM                  30   
1       JC113627  01/11/2019 11:36:00 PM                  30   
2       JC113637  01/11/2019 11:31:00 PM                  15   
3       JC113630  01/11/2019 11:22:00 PM                  35   
4       JC113604  01/11/2019 11:08:00 PM                  30   
...          ...                     ...                 ...   
257920  HY498942  11/11/2014 08:00:00 PM                  30   
257921  HZ400518  08/20/2014 04:50:00 PM                   0   
257922  HZ164689  02/24/2014 07:45:00 PM                  30   
257923  HZ122950  01/21/2014 07:40:00 AM                  30   
257924  JB442550  01/18/2014 06:14:00 PM                  30   

       TRAFFIC_CONTROL_DEVICE      DEVICE_CONDITION WEATHER_CONDITION  \
0                 NO CONTROLS           NO CONTROLS             CLEAR   
1           STOP SIGN/FLASHER  FUNCTIONING PROPERLY             CLEAR   
2           STOP SIGN/FLASHER  FUNCTIONING PROPERLY             CLEAR   
3                 NO CONTROLS           NO CONTROLS             CLEAR   
4              TRAFFIC SIGNAL  FUNCTIONING PROPERLY             CLEAR   
...                       ...                   ...               ...   
257920            NO CONTROLS           NO CONTROLS           UNKNOWN   
257921            NO CONTROLS           NO CONTROLS             CLEAR   
257922         TRAFFIC SIGNAL  FUNCTIONING PROPERLY              RAIN   
257923                  YIELD           NO CONTROLS             CLEAR   
257924            NO CONTROLS           NO CONTROLS             CLEAR   

            LIGHTING_CONDITION              FIRST_CRASH_TYPE  \
0       DARKNESS, LIGHTED ROAD          PARKED MOTOR VEHICLE   
1       DARKNESS, LIGHTED ROAD                         ANGLE   
2                     DARKNESS  SIDESWIPE OPPOSITE DIRECTION   
3                     DARKNESS          PARKED MOTOR VEHICLE   
4       DARKNESS, LIGHTED ROAD                      REAR END   
...                        ...                           ...   
257920                 UNKNOWN          PARKED MOTOR VEHICLE   
257921                DAYLIGHT                      REAR END   
257922                DAYLIGHT                       TURNING   
257923                DAYLIGHT                         ANGLE   
257924                    DUSK          PARKED MOTOR VEHICLE   

                        TRAFFICWAY_TYPE           ALIGNMENT  ...  \
0                           NOT DIVIDED  STRAIGHT AND LEVEL  ...   
1                           NOT DIVIDED  STRAIGHT AND LEVEL  ...   
2                           NOT DIVIDED  STRAIGHT AND LEVEL  ...   
3                           NOT DIVIDED  STRAIGHT AND LEVEL  ...   
4                           NOT DIVIDED  STRAIGHT AND LEVEL  ...   
...                                 ...                 ...  ...   
257920  DIVIDED - W/MEDIAN (NOT RAISED)  STRAIGHT AND LEVEL  ...   
257921                      NOT DIVIDED  STRAIGHT AND LEVEL  ...   
257922                      NOT DIVIDED  STRAIGHT AND LEVEL  ...   
257923  DIVIDED - W/MEDIAN (NOT RAISED)  STRAIGHT AND LEVEL  ...   
257924       DIVIDED - W/MEDIAN BARRIER  STRAIGHT AND LEVEL  ...   

       INJURIES_NON_INCAPACITATING INJURIES_REPORTED_NOT_EVIDENT  \
0                              0.0                           0.0   
1                              0.0                           0.0   
2                              0.0                           0.0   
3                              0.0                           0.0   
4                              0.0                           0.0   
...                            ...                           ...   
257920                         0.0                           0.0   
257921                         0.0                           0.0   
257922                         0.0                           0.0   
257923                         1.0                           0.0   
257924                         

In [24]:
cc= crashes[crashes['BEAT_OF_OCCURRENCE'].isnull()]
cc

RD_NO              CRASH_DATE  POSTED_SPEED_LIMIT  \
204846  HZ562684  12/23/2016 12:30:00 PM                  30   
206421  HZ552745  12/15/2016 03:10:00 PM                  30   
216083  HZ478865  10/17/2016 09:00:00 AM                  30   
216644  HZ472928  10/13/2016 03:40:00 PM                  35   

       TRAFFIC_CONTROL_DEVICE DEVICE_CONDITION WEATHER_CONDITION  \
204846            NO CONTROLS      NO CONTROLS             CLEAR   
206421            NO CONTROLS      NO CONTROLS             CLEAR   
216083            NO CONTROLS      NO CONTROLS           UNKNOWN   
216644            NO CONTROLS      NO CONTROLS             CLEAR   

       LIGHTING_CONDITION FIRST_CRASH_TYPE                  TRAFFICWAY_TYPE  \
204846           DAYLIGHT         REAR END                      NOT DIVIDED   
206421           DAYLIGHT         REAR END  DIVIDED - W/MEDIAN (NOT RAISED)   
216083            UNKNOWN         REAR END  DIVIDED - W/MEDIAN (NOT RAISED)   
216644           DAYLIGHT         REAR END                      NOT DIVIDED   

                 ALIGNMENT  ... INJURIES_NON_INCAPACITATING  \
204846  STRAIGHT AND LEVEL  ...                         0.0   
206421  STRAIGHT AND LEVEL  ...                         0.0   
216083  STRAIGHT AND LEVEL  ...                         0.0   
216644  STRAIGHT AND LEVEL  ...                         0.0   

       INJURIES_REPORTED_NOT_EVIDENT INJURIES_NO_INDICATION INJURIES_UNKNOWN  \
204846                           0.0                    3.0              0.0   
206421                           0.0                    2.0              0.0   
216083                           0.0                    2.0              0.0   
216644                           0.0                    2.0              0.0   

       CRASH_HOUR CRASH_DAY_OF_WEEK CRASH_MONTH   LATITUDE  LONGITUDE  \
204846         12                 6          12  41.780148 -87.614552   
206421         15                 5          12  41.786811 -87.653621   
216083          9                 2          10        NaN        NaN   
216644         15                 5          10  41.994542 -87.713897   

                                        LOCATION  
204846  POINT (-87.614552135332 41.780148264311)  
206421  POINT (-87.653621088745 41.786811402722)  
216083                                       NaN  
216644  POINT (-87.713896783814 41.994542305274)  

[4 rows x 36 columns]

In [5]:
crashes['MOST_SEVERE_INJURY'].value_counts()

MOST_SEVERE_INJURY
NO INDICATION OF INJURY     228475
NONINCAPACITATING INJURY     15808
REPORTED, NOT EVIDENT         9703
INCAPACITATING INJURY         3723
FATAL                          209
Name: count, dtype: int64

In [67]:
# LE RIGHE CHE NON HANNO MOST SEVERE INJURY NON HANNO 0 PER TOTAL INJURY, QUINDI ANHCE I SEVERE SARANNO 0

most_sev = crashes[crashes['MOST_SEVERE_INJURY'].isnull()]
most_sev[['INJURIES_TOTAL', 'INJURIES_FATAL', 'INJURIES_INCAPACITATING',
          'INJURIES_NON_INCAPACITATING', 'INJURIES_REPORTED_NOT_EVIDENT']]

INJURIES_TOTAL  INJURIES_FATAL  INJURIES_INCAPACITATING  \
14205              0.0             0.0                      0.0   
25482              0.0             0.0                      0.0   
146939             0.0             0.0                      0.0   
160254             0.0             0.0                      0.0   
185417             0.0             0.0                      0.0   
231203             0.0             0.0                      0.0   
243782             0.0             0.0                      0.0   

        INJURIES_NON_INCAPACITATING  INJURIES_REPORTED_NOT_EVIDENT  
14205                           0.0                            0.0  
25482                           0.0                            0.0  
146939                          0.0                            0.0  
160254                          0.0                            0.0  
185417                          0.0                            0.0  
231203                          0.0                            0.0  
243782                          0.0                            0.0

Siccome gli incidenti che hanno valori nulli in 'MOST_SEVERE_INJURY' non hanno feriti, possiamo dedurre che i feriti gravi siano 0 a loro volta.

In [79]:
crashes[crashes['REPORT_TYPE'].isnull()]

RD_NO              CRASH_DATE  POSTED_SPEED_LIMIT  \
261     JC111906  01/10/2019 04:20:00 PM                  30   
340     JC111380  01/10/2019 08:25:00 AM                  30   
358     JC111967  01/10/2019 07:00:00 AM                  30   
465     JC110718  01/09/2019 03:15:00 PM                  30   
543     JC110198  01/09/2019 09:30:00 AM                  30   
...          ...                     ...                 ...   
256278  HY437811  09/25/2015 12:05:00 PM                  30   
256417  HY433982  09/22/2015 04:40:00 PM                  99   
257669  HY392560  08/21/2015 02:45:00 PM                  30   
257764  HY386254  08/15/2015 11:15:00 PM                  30   
257912  JB278951  05/25/2015 11:38:00 PM                  30   

       TRAFFIC_CONTROL_DEVICE      DEVICE_CONDITION WEATHER_CONDITION  \
261         STOP SIGN/FLASHER           NO CONTROLS             CLEAR   
340               NO CONTROLS           NO CONTROLS             CLEAR   
358            TRAFFIC SIGNAL  FUNCTIONING PROPERLY             CLEAR   
465         STOP SIGN/FLASHER  FUNCTIONING PROPERLY             CLEAR   
543            TRAFFIC SIGNAL  FUNCTIONING PROPERLY             CLEAR   
...                       ...                   ...               ...   
256278            NO CONTROLS           NO CONTROLS             CLEAR   
256417            NO CONTROLS           NO CONTROLS             CLEAR   
257669            NO CONTROLS           NO CONTROLS             CLEAR   
257764         TRAFFIC SIGNAL  FUNCTIONING PROPERLY             CLEAR   
257912      STOP SIGN/FLASHER  FUNCTIONING PROPERLY             CLEAR   

            LIGHTING_CONDITION          FIRST_CRASH_TYPE  \
261                       DUSK                     ANGLE   
340                   DAYLIGHT  SIDESWIPE SAME DIRECTION   
358     DARKNESS, LIGHTED ROAD                PEDESTRIAN   
465                   DAYLIGHT              PEDALCYCLIST   
543                   DAYLIGHT                     ANGLE   
...                        ...                       ...   
256278                DAYLIGHT              FIXED OBJECT   
256417                DAYLIGHT  SIDESWIPE SAME DIRECTION   
257669                DAYLIGHT  SIDESWIPE SAME DIRECTION   
257764  DARKNESS, LIGHTED ROAD                  REAR END   
257912  DARKNESS, LIGHTED ROAD                   HEAD ON   

                        TRAFFICWAY_TYPE           ALIGNMENT  ...  \
261                         NOT DIVIDED  STRAIGHT AND LEVEL  ...   
340                         NOT DIVIDED  STRAIGHT AND LEVEL  ...   
358                         NOT DIVIDED  STRAIGHT AND LEVEL  ...   
465                             ONE-WAY  STRAIGHT AND LEVEL  ...   
543                         NOT DIVIDED  STRAIGHT AND LEVEL  ...   
...                                 ...                 ...  ...   
256278  DIVIDED - W/MEDIAN (NOT RAISED)  STRAIGHT AND LEVEL  ...   
256417                          UNKNOWN  STRAIGHT AND LEVEL  ...   
257669                      NOT DIVIDED  STRAIGHT AND LEVEL  ...   
257764  DIVIDED - W/MEDIAN (NOT RAISED)  STRAIGHT AND LEVEL  ...   
257912  DIVIDED - W/MEDIAN (NOT RAISED)  STRAIGHT AND LEVEL  ...   

       INJURIES_NON_INCAPACITATING INJURIES_REPORTED_NOT_EVIDENT  \
261                            0.0                           0.0   
340                            0.0                           0.0   
358                            0.0                           1.0   
465                            0.0                           0.0   
543                            0.0                           0.0   
...                            ...                           ...   
256278                         0.0                           0.0   
256417                         0.0                           0.0   
257669                         0.0                           0.0   
257764                         0.0                           0.0   
257912                         0.0                           0.0   

       INJ

In [4]:
on_scene = crashes[crashes['REPORT_TYPE'] == 'ON SCENE']
on_scene

RD_NO              CRASH_DATE  POSTED_SPEED_LIMIT  \
0       JC113649  01/12/2019 12:01:00 AM                  30   
1       JC113627  01/11/2019 11:36:00 PM                  30   
3       JC113630  01/11/2019 11:22:00 PM                  35   
5       JC113579  01/11/2019 10:45:00 PM                  30   
6       JC113617  01/11/2019 10:28:00 PM                  35   
...          ...                     ...                 ...   
257615  HY394718  08/23/2015 06:40:00 PM                  30   
257735  HY386623  08/17/2015 05:45:00 PM                  30   
257830  HY376806  08/10/2015 12:48:00 PM                  30   
257876  HY372735  08/05/2015 02:30:00 PM                  30   
257923  HZ122950  01/21/2014 07:40:00 AM                  30   

       TRAFFIC_CONTROL_DEVICE      DEVICE_CONDITION WEATHER_CONDITION  \
0                 NO CONTROLS           NO CONTROLS             CLEAR   
1           STOP SIGN/FLASHER  FUNCTIONING PROPERLY             CLEAR   
3                 NO CONTROLS           NO CONTROLS             CLEAR   
5                 NO CONTROLS           NO CONTROLS             CLEAR   
6                 NO CONTROLS           NO CONTROLS             CLEAR   
...                       ...                   ...               ...   
257615            NO CONTROLS           NO CONTROLS             CLEAR   
257735            NO CONTROLS           NO CONTROLS             CLEAR   
257830            NO CONTROLS           NO CONTROLS             CLEAR   
257876            NO CONTROLS           NO CONTROLS             CLEAR   
257923                  YIELD           NO CONTROLS             CLEAR   

            LIGHTING_CONDITION          FIRST_CRASH_TYPE  \
0       DARKNESS, LIGHTED ROAD      PARKED MOTOR VEHICLE   
1       DARKNESS, LIGHTED ROAD                     ANGLE   
3                     DARKNESS      PARKED MOTOR VEHICLE   
5       DARKNESS, LIGHTED ROAD                  REAR END   
6       DARKNESS, LIGHTED ROAD                  REAR END   
...                        ...                       ...   
257615                DAYLIGHT                   TURNING   
257735                DAYLIGHT      PARKED MOTOR VEHICLE   
257830                DAYLIGHT      PARKED MOTOR VEHICLE   
257876                DAYLIGHT  SIDESWIPE SAME DIRECTION   
257923                DAYLIGHT                     ANGLE   

                        TRAFFICWAY_TYPE           ALIGNMENT  ...  \
0                           NOT DIVIDED  STRAIGHT AND LEVEL  ...   
1                           NOT DIVIDED  STRAIGHT AND LEVEL  ...   
3                           NOT DIVIDED  STRAIGHT AND LEVEL  ...   
5                           NOT DIVIDED  STRAIGHT AND LEVEL  ...   
6                           NOT DIVIDED  STRAIGHT AND LEVEL  ...   
...                                 ...                 ...  ...   
257615                      NOT DIVIDED  STRAIGHT AND LEVEL  ...   
257735       DIVIDED - W/MEDIAN BARRIER  STRAIGHT AND LEVEL  ...   
257830                          ONE-WAY  STRAIGHT AND LEVEL  ...   
257876  DIVIDED - W/MEDIAN (NOT RAISED)  STRAIGHT AND LEVEL  ...   
257923  DIVIDED - W/MEDIAN (NOT RAISED)  STRAIGHT AND LEVEL  ...   

       INJURIES_NON_INCAPACITATING INJURIES_REPORTED_NOT_EVIDENT  \
0                              0.0                           0.0   
1                              0.0                           0.0   
3                              0.0                           0.0   
5                              0.0                           0.0   
6                              0.0                           0.0   
...                            ...                           ...   
257615                         0.0                           0.0   
257735                         0.0                           0.0   
257830                         0.0                           0.0   
257876                         0.0                           0.0   
257923                         1.0                           0.0   

       INJ

In [6]:
crashes['REPORT_TYPE'].value_counts()

REPORT_TYPE
NOT ON SCENE (DESK REPORT)    167961
ON SCENE                       84968
Name: count, dtype: int64

In [20]:
new_df = crashes[crashes['REPORT_TYPE'].isnull()]
new_df

RD_NO              CRASH_DATE  POSTED_SPEED_LIMIT  \
261     JC111906  01/10/2019 04:20:00 PM                  30   
340     JC111380  01/10/2019 08:25:00 AM                  30   
358     JC111967  01/10/2019 07:00:00 AM                  30   
465     JC110718  01/09/2019 03:15:00 PM                  30   
543     JC110198  01/09/2019 09:30:00 AM                  30   
...          ...                     ...                 ...   
256278  HY437811  09/25/2015 12:05:00 PM                  30   
256417  HY433982  09/22/2015 04:40:00 PM                  99   
257669  HY392560  08/21/2015 02:45:00 PM                  30   
257764  HY386254  08/15/2015 11:15:00 PM                  30   
257912  JB278951  05/25/2015 11:38:00 PM                  30   

       TRAFFIC_CONTROL_DEVICE      DEVICE_CONDITION WEATHER_CONDITION  \
261         STOP SIGN/FLASHER           NO CONTROLS             CLEAR   
340               NO CONTROLS           NO CONTROLS             CLEAR   
358            TRAFFIC SIGNAL  FUNCTIONING PROPERLY             CLEAR   
465         STOP SIGN/FLASHER  FUNCTIONING PROPERLY             CLEAR   
543            TRAFFIC SIGNAL  FUNCTIONING PROPERLY             CLEAR   
...                       ...                   ...               ...   
256278            NO CONTROLS           NO CONTROLS             CLEAR   
256417            NO CONTROLS           NO CONTROLS             CLEAR   
257669            NO CONTROLS           NO CONTROLS             CLEAR   
257764         TRAFFIC SIGNAL  FUNCTIONING PROPERLY             CLEAR   
257912      STOP SIGN/FLASHER  FUNCTIONING PROPERLY             CLEAR   

            LIGHTING_CONDITION          FIRST_CRASH_TYPE  \
261                       DUSK                     ANGLE   
340                   DAYLIGHT  SIDESWIPE SAME DIRECTION   
358     DARKNESS, LIGHTED ROAD                PEDESTRIAN   
465                   DAYLIGHT              PEDALCYCLIST   
543                   DAYLIGHT                     ANGLE   
...                        ...                       ...   
256278                DAYLIGHT              FIXED OBJECT   
256417                DAYLIGHT  SIDESWIPE SAME DIRECTION   
257669                DAYLIGHT  SIDESWIPE SAME DIRECTION   
257764  DARKNESS, LIGHTED ROAD                  REAR END   
257912  DARKNESS, LIGHTED ROAD                   HEAD ON   

                        TRAFFICWAY_TYPE           ALIGNMENT  ...  \
261                         NOT DIVIDED  STRAIGHT AND LEVEL  ...   
340                         NOT DIVIDED  STRAIGHT AND LEVEL  ...   
358                         NOT DIVIDED  STRAIGHT AND LEVEL  ...   
465                             ONE-WAY  STRAIGHT AND LEVEL  ...   
543                         NOT DIVIDED  STRAIGHT AND LEVEL  ...   
...                                 ...                 ...  ...   
256278  DIVIDED - W/MEDIAN (NOT RAISED)  STRAIGHT AND LEVEL  ...   
256417                          UNKNOWN  STRAIGHT AND LEVEL  ...   
257669                      NOT DIVIDED  STRAIGHT AND LEVEL  ...   
257764  DIVIDED - W/MEDIAN (NOT RAISED)  STRAIGHT AND LEVEL  ...   
257912  DIVIDED - W/MEDIAN (NOT RAISED)  STRAIGHT AND LEVEL  ...   

       INJURIES_NON_INCAPACITATING INJURIES_REPORTED_NOT_EVIDENT  \
261                            0.0                           0.0   
340                            0.0                           0.0   
358                            0.0                           1.0   
465                            0.0                           0.0   
543                            0.0                           0.0   
...                            ...                           ...   
256278                         0.0                           0.0   
256417                         0.0                           0.0   
257669                         0.0                           0.0   
257764                         0.0                           0.0   
257912                         0.0                           0.0   

       INJ

In [10]:
null_street_name = crashes[crashes['STREET_NAME'].isnull()]
null_street_name

RD_NO              CRASH_DATE  POSTED_SPEED_LIMIT  \
226526  HZ386509  08/10/2016 02:20:00 PM                  30   

       TRAFFIC_CONTROL_DEVICE DEVICE_CONDITION WEATHER_CONDITION  \
226526            NO CONTROLS      NO CONTROLS             CLEAR   

       LIGHTING_CONDITION FIRST_CRASH_TYPE TRAFFICWAY_TYPE  \
226526           DAYLIGHT         REAR END     NOT DIVIDED   

                 ALIGNMENT  ... INJURIES_NON_INCAPACITATING  \
226526  STRAIGHT AND LEVEL  ...                         0.0   

       INJURIES_REPORTED_NOT_EVIDENT INJURIES_NO_INDICATION INJURIES_UNKNOWN  \
226526                           0.0                    2.0              0.0   

       CRASH_HOUR CRASH_DAY_OF_WEEK CRASH_MONTH  LATITUDE LONGITUDE LOCATION  
226526         14                 4           8       NaN       NaN      NaN  

[1 rows x 36 columns]

In [14]:
null_street_name[['STREET_NO', 'STREET_DIRECTION', 'BEAT_OF_OCCURRENCE']]

STREET_NO STREET_DIRECTION  BEAT_OF_OCCURRENCE
226526        532                E               624.0

In [49]:
filtered_crashes = crashes[(crashes['STREET_NO'] == 532) & 
                           (crashes['STREET_DIRECTION'] == 'E') & 
                           (crashes['BEAT_OF_OCCURRENCE'] == 624.0)]
filtered_crashes['STREET_NAME']

78186     76TH ST
222771    76TH ST
226526        NaN
Name: STREET_NAME, dtype: object

Street direction

In [24]:
null_street_dir = crashes[crashes['STREET_DIRECTION'].isnull()]
null_street_dir['STREET_NAME']

180006           DOTY AVE W
216083    BESSIE COLEMAN DR
Name: STREET_NAME, dtype: object

In [7]:
dotyave = crashes[crashes['STREET_NAME'] == 'DOTY AVE W']
dotyave['STREET_DIRECTION'].value_counts()

STREET_DIRECTION
S    91
Name: count, dtype: int64

In [8]:
dotyave = crashes[crashes['STREET_NAME'] == 'BESSIE COLEMAN DR']
dotyave['STREET_DIRECTION'].value_counts()

STREET_DIRECTION
N    32
Name: count, dtype: int64

riga 180006 STREET_NAME DOTY AVE W - STREET_DIRECTION S

riga 216083 STREET_NAME BESSIE COLEMAN DR - STREET_DIRECTION N

In [35]:
null_beat_occ = crashes[crashes['BEAT_OF_OCCURRENCE'].isnull()]
null_beat_occ[['STREET_NAME', 'STREET_DIRECTION', 'STREET_NO', 'LOCATION', 'BEAT_OF_OCCURRENCE']]

STREET_NAME STREET_DIRECTION  STREET_NO  \
204846            63RD ST                E        425   
206421             MAY ST                S       5900   
216083  BESSIE COLEMAN DR              NaN      10000   
216644        LINCOLN AVE                N       6199   

                                        LOCATION  BEAT_OF_OCCURRENCE  
204846  POINT (-87.614552135332 41.780148264311)                 NaN  
206421  POINT (-87.653621088745 41.786811402722)                 NaN  
216083                                       NaN                 NaN  
216644  POINT (-87.713896783814 41.994542305274)                 NaN

In [34]:
bess = crashes[crashes['STREET_NAME']=='BESSIE COLEMAN DR']
bess['BEAT_OF_OCCURRENCE'].value_counts()

BEAT_OF_OCCURRENCE
1654.0    32
Name: count, dtype: int64

In [51]:
strada1 = crashes[(crashes['STREET_NAME'] == '63RD ST') &  (crashes['STREET_NO'] == 425)]
strada1 = strada1[strada1['STREET_DIRECTION'] == 'E']

strada1['BEAT_OF_OCCURRENCE'].value_counts()

BEAT_OF_OCCURRENCE
312.0    3
Name: count, dtype: int64

In [54]:
strada2 = crashes[(crashes['STREET_NAME'] == 'MAY ST') & (crashes['STREET_NO'] == 5900)]

strada2['BEAT_OF_OCCURRENCE'].value_counts()

BEAT_OF_OCCURRENCE
712.0    3
Name: count, dtype: int64

In [56]:
strada3 = crashes[crashes['STREET_NAME'] == 'BESSIE COLEMAN DR' ]
strada3['BEAT_OF_OCCURRENCE'].value_counts()

BEAT_OF_OCCURRENCE
1654.0    32
Name: count, dtype: int64

In [58]:
strada4 = crashes[(crashes['STREET_NAME'] == 'LINCOLN AVE') & (crashes['STREET_NO'] == 6199)]

strada4['BEAT_OF_OCCURRENCE'].value_counts()

BEAT_OF_OCCURRENCE
1711.0    6
Name: count, dtype: int64

In [8]:
# Inizializza un dizionario per memorizzare i risultati
street_coordinates = {}

street_names = [
    "CHICAGO SKYWAY OB",
    "CHICAGO SKYWAY IB",
    "TERMINAL ST",
    "DR MARTIN LUTHER KING JR SD",
    "OHARE ST",
    "I190 EXPY",
    "OGDEN SD",
    "KENNEDY EXPY IB",
    "PARKING LOT A ST",
    "PARKING LOT G ST",
    "PARKING LOT D ST",
    "MC FETRIDGE DR",
    "RANDOLPH SUB ST",
    "DAN RYAN LOCAL OB",
    "LA SALLE DR",
    "MANNHEIM RD",
    "LOGAN SD",
    "LA SALLE DR /ILLINOIS",
    "SOUTH WATER RAMP",
    "LAWERENCE",
    "N BELMONT AVE LSD XR",
    "MICHIGAN AVE XR",
    "KENNEDY EXPY OB",
    "87TH ST",
    "KEDVALE AVE",
    "LAKE SHORE DR NB",
    "BESSIE COLEMAN DR",
    "DAN RYAN XPRS OB",
    "SHERMAN PARK SD N",
    "ARCHER/LEAVIT",
    "DAMEN AVE VIA",
    "GARLAND CT / LAKE STREET",
    "RWY 22L",
    "MICHIGAN AVE 175 E CHESTNUT AVE",
    "LAKE LOWER ST",
    "DOTY AVE E",
    "UNION ST",
    "WACKER SUB DR",
    "87TH SD",
    "FRANKLIN SD"
]

# Itera per ciascun nome di strada
for street in street_names:
    # Filtra i dati per la strada corrente
    street_data = crashes[crashes['STREET_NAME'] == street]
    # Considera solo le righe con valori di posizione non nulli
    street_data_loc = street_data[street_data['LOCATION'].notnull()]
    
    # Calcola le medie di latitudine e longitudine
    lat_mean = street_data_loc['LATITUDE'].mean()
    lon_mean = street_data_loc['LONGITUDE'].mean()
    
    # Salva i risultati nel dizionario
    street_coordinates[street] = {'latitude': lat_mean, 'longitude': lon_mean}

# Il dizionario 'street_coordinates' contiene ora le coordinate medie per ogni strada


In [9]:
street_coordinates

{'CHICAGO SKYWAY OB': {'latitude': 41.74227883457143,
  'longitude': -87.57590929792856},
 'CHICAGO SKYWAY IB': {'latitude': 41.74227353683332,
  'longitude': -87.57654492987038},
 'TERMINAL ST': {'latitude': nan, 'longitude': nan},
 'DR MARTIN LUTHER KING JR SD': {'latitude': nan, 'longitude': nan},
 'OHARE ST': {'latitude': 41.97620113900001, 'longitude': -87.90530912500004},
 'I190 EXPY': {'latitude': nan, 'longitude': nan},
 'OGDEN SD': {'latitude': nan, 'longitude': nan},
 'KENNEDY EXPY IB': {'latitude': 41.9445149038,
  'longitude': -87.74905055459999},
 'PARKING LOT A ST': {'latitude': nan, 'longitude': nan},
 'PARKING LOT G ST': {'latitude': nan, 'longitude': nan},
 'PARKING LOT D ST': {'latitude': nan, 'longitude': nan},
 'MC FETRIDGE DR': {'latitude': 41.865043402551734,
  'longitude': -87.6173671586207},
 'RANDOLPH SUB ST': {'latitude': 41.884592989666665,
  'longitude': -87.62160521266667},
 'DAN RYAN LOCAL OB': {'latitude': nan, 'longitude': nan},
 'LA SALLE DR': {'latitud

In [49]:
people['PERSON_ID']

0         O561555
1         O561563
2         O561564
3         O561540
4         O561541
           ...   
564560     O30751
564561     O24495
564562     O24496
564563    O481321
564564    P108071
Name: PERSON_ID, Length: 564565, dtype: object

In [51]:
vehicles['CRASH_UNIT_ID']

0         561555
1         561563
2         561564
3         561540
4         561541
           ...  
460432     30751
460433     24495
460434     24496
460435    481321
460436    481322
Name: CRASH_UNIT_ID, Length: 460437, dtype: int64

In [52]:
crashes

RD_NO              CRASH_DATE  POSTED_SPEED_LIMIT  \
0       JC113649  01/12/2019 12:01:00 AM                  30   
1       JC113627  01/11/2019 11:36:00 PM                  30   
2       JC113637  01/11/2019 11:31:00 PM                  15   
3       JC113630  01/11/2019 11:22:00 PM                  35   
4       JC113604  01/11/2019 11:08:00 PM                  30   
...          ...                     ...                 ...   
257920  HY498942  11/11/2014 08:00:00 PM                  30   
257921  HZ400518  08/20/2014 04:50:00 PM                   0   
257922  HZ164689  02/24/2014 07:45:00 PM                  30   
257923  HZ122950  01/21/2014 07:40:00 AM                  30   
257924  JB442550  01/18/2014 06:14:00 PM                  30   

       TRAFFIC_CONTROL_DEVICE      DEVICE_CONDITION WEATHER_CONDITION  \
0                 NO CONTROLS           NO CONTROLS             CLEAR   
1           STOP SIGN/FLASHER  FUNCTIONING PROPERLY             CLEAR   
2           STOP SIGN/FLASHER  FUNCTIONING PROPERLY             CLEAR   
3                 NO CONTROLS           NO CONTROLS             CLEAR   
4              TRAFFIC SIGNAL  FUNCTIONING PROPERLY             CLEAR   
...                       ...                   ...               ...   
257920            NO CONTROLS           NO CONTROLS           UNKNOWN   
257921            NO CONTROLS           NO CONTROLS             CLEAR   
257922         TRAFFIC SIGNAL  FUNCTIONING PROPERLY              RAIN   
257923                  YIELD           NO CONTROLS             CLEAR   
257924            NO CONTROLS           NO CONTROLS             CLEAR   

            LIGHTING_CONDITION              FIRST_CRASH_TYPE  \
0       DARKNESS, LIGHTED ROAD          PARKED MOTOR VEHICLE   
1       DARKNESS, LIGHTED ROAD                         ANGLE   
2                     DARKNESS  SIDESWIPE OPPOSITE DIRECTION   
3                     DARKNESS          PARKED MOTOR VEHICLE   
4       DARKNESS, LIGHTED ROAD                      REAR END   
...                        ...                           ...   
257920                 UNKNOWN          PARKED MOTOR VEHICLE   
257921                DAYLIGHT                      REAR END   
257922                DAYLIGHT                       TURNING   
257923                DAYLIGHT                         ANGLE   
257924                    DUSK          PARKED MOTOR VEHICLE   

                        TRAFFICWAY_TYPE           ALIGNMENT  ...  \
0                           NOT DIVIDED  STRAIGHT AND LEVEL  ...   
1                           NOT DIVIDED  STRAIGHT AND LEVEL  ...   
2                           NOT DIVIDED  STRAIGHT AND LEVEL  ...   
3                           NOT DIVIDED  STRAIGHT AND LEVEL  ...   
4                           NOT DIVIDED  STRAIGHT AND LEVEL  ...   
...                                 ...                 ...  ...   
257920  DIVIDED - W/MEDIAN (NOT RAISED)  STRAIGHT AND LEVEL  ...   
257921                      NOT DIVIDED  STRAIGHT AND LEVEL  ...   
257922                      NOT DIVIDED  STRAIGHT AND LEVEL  ...   
257923  DIVIDED - W/MEDIAN (NOT RAISED)  STRAIGHT AND LEVEL  ...   
257924       DIVIDED - W/MEDIAN BARRIER  STRAIGHT AND LEVEL  ...   

       INJURIES_NON_INCAPACITATING INJURIES_REPORTED_NOT_EVIDENT  \
0                              0.0                           0.0   
1                              0.0                           0.0   
2                              0.0                           0.0   
3                              0.0                           0.0   
4                              0.0                           0.0   
...                            ...                           ...   
257920                         0.0                           0.0   
257921                         0.0                           0.0   
257922                         0.0                           0.0   
257923                         1.0                           0.0   
257924                         

In [55]:
aa = vehicles['CRASH_UNIT_ID'].value_counts()
aa.max()

1

In [53]:
vehicles['RD_NO'] == 'JC113649'

0          True
1         False
2         False
3         False
4         False
          ...  
460432    False
460433    False
460434    False
460435    False
460436    False
Name: RD_NO, Length: 460437, dtype: bool

# PEOPLE DATASET

In [40]:
people.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 564565 entries, 0 to 564564
Data columns (total 19 columns):
 #   Column                 Non-Null Count   Dtype  
---  ------                 --------------   -----  
 0   PERSON_ID              564565 non-null  object 
 1   PERSON_TYPE            564565 non-null  object 
 2   RD_NO                  564565 non-null  object 
 3   VEHICLE_ID             553869 non-null  float64
 4   CRASH_DATE             564565 non-null  object 
 5   CITY                   420645 non-null  object 
 6   STATE                  422589 non-null  object 
 7   SEX                    557411 non-null  object 
 8   AGE                    403584 non-null  float64
 9   SAFETY_EQUIPMENT       563155 non-null  object 
 10  AIRBAG_DEPLOYED        554113 non-null  object 
 11  EJECTION               557860 non-null  object 
 12  INJURY_CLASSIFICATION  564269 non-null  object 
 13  DRIVER_ACTION          454799 non-null  object 
 14  DRIVER_VISION          454681 non-nu

In [47]:
vehicles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 460437 entries, 0 to 460436
Data columns (total 17 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   CRASH_UNIT_ID        460437 non-null  int64  
 1   RD_NO                460437 non-null  object 
 2   CRASH_DATE           460437 non-null  object 
 3   UNIT_NO              460437 non-null  int64  
 4   UNIT_TYPE            460436 non-null  object 
 5   VEHICLE_ID           450064 non-null  float64
 6   MAKE                 450064 non-null  object 
 7   MODEL                448651 non-null  object 
 8   LIC_PLATE_STATE      410808 non-null  object 
 9   VEHICLE_YEAR         371782 non-null  float64
 10  VEHICLE_DEFECT       450064 non-null  object 
 11  VEHICLE_TYPE         450064 non-null  object 
 12  VEHICLE_USE          450064 non-null  object 
 13  TRAVEL_DIRECTION     450064 non-null  object 
 14  MANEUVER             450064 non-null  object 
 15  OCCUPANT_CNT     

In [101]:
people = pd.read_csv('C:/Users/al797/Desktop/People.csv')

In [54]:
people.columns

Index(['PERSON_ID', 'PERSON_TYPE', 'RD_NO', 'VEHICLE_ID', 'CRASH_DATE', 'CITY',
       'STATE', 'SEX', 'AGE', 'SAFETY_EQUIPMENT', 'AIRBAG_DEPLOYED',
       'EJECTION', 'INJURY_CLASSIFICATION', 'DRIVER_ACTION', 'DRIVER_VISION',
       'PHYSICAL_CONDITION', 'BAC_RESULT', 'DAMAGE_CATEGORY', 'DAMAGE'],
      dtype='object')

In [103]:
people.head()

PERSON_ID PERSON_TYPE     RD_NO  VEHICLE_ID              CRASH_DATE  \
0   O561555      DRIVER  JC113649    535742.0  01/12/2019 12:01:00 AM   
1   O561563      DRIVER  JC113627    535738.0  01/11/2019 11:36:00 PM   
2   O561564      DRIVER  JC113627    535741.0  01/11/2019 11:36:00 PM   
3   O561540      DRIVER  JC113637    535714.0  01/11/2019 11:31:00 PM   
4   O561541      DRIVER  JC113637    535718.0  01/11/2019 11:31:00 PM   

      CITY STATE SEX   AGE  SAFETY_EQUIPMENT     AIRBAG_DEPLOYED EJECTION  \
0      NaN   NaN   X   NaN     USAGE UNKNOWN  DEPLOYMENT UNKNOWN  UNKNOWN   
1  CHICAGO    IL   M  63.0     USAGE UNKNOWN      DID NOT DEPLOY     NONE   
2  CHICAGO    IL   M  36.0     USAGE UNKNOWN      DID NOT DEPLOY     NONE   
3      NaN   NaN   F   NaN     USAGE UNKNOWN  DEPLOYMENT UNKNOWN     NONE   
4  CHICAGO    IL   F  31.0  SAFETY BELT USED      DID NOT DEPLOY     NONE   

     INJURY_CLASSIFICATION                DRIVER_ACTION DRIVER_VISION  \
0  NO INDICATION OF INJURY                      UNKNOWN       UNKNOWN   
1  NO INDICATION OF INJURY                         NONE  NOT OBSCURED   
2  NO INDICATION OF INJURY  DISREGARDED CONTROL DEVICES  NOT OBSCURED   
3  NO INDICATION OF INJURY                         NONE       UNKNOWN   
4  NO INDICATION OF INJURY                         NONE  NOT OBSCURED   

   PHYSICAL_CONDITION                       BAC_RESULT DAMAGE_CATEGORY  \
0             UNKNOWN                 TEST NOT OFFERED     OVER $1,500   
1              NORMAL                 TEST NOT OFFERED     OVER $1,500   
2  IMPAIRED - ALCOHOL  TEST PERFORMED, RESULTS UNKNOWN     OVER $1,500   
3             UNKNOWN                 TEST NOT OFFERED     OVER $1,500   
4              NORMAL                 TEST NOT OFFERED     OVER $1,500   

        DAMAGE  
0  6069.089569  
1  6237.638447  
2  3802.304187  
3  3127.680131  
4  2225.886815


VEHICLE_ID                10696
CITY                     143920
STATE                    141976
SEX                        7154
AGE                      160981
SAFETY_EQUIPMENT           1410
AIRBAG_DEPLOYED           10452
EJECTION                   6705
INJURY_CLASSIFICATION       296
DRIVER_ACTION            109766
DRIVER_VISION            109884


### NO VEHICLE: PEDESTRIANS?

In [114]:
novc = people[people['VEHICLE_ID'].isnull()]
person_type_counts = novc['PERSON_TYPE'].value_counts()
person_type_counts

PERSON_TYPE
PEDESTRIAN             6352
BICYCLE                3799
NON-MOTOR VEHICLE       496
NON-CONTACT VEHICLE      43
DRIVER                    6
Name: count, dtype: int64

per i pedoni, bici e non motorizzati mettiamo 0 al vehicle id, per driver e non-contact?

#### SAFETY_EQUIPMENT , AIRBAG_DEPLOYED, EJECTION  possono essere messi a 0 per i pedoni, bici, non veichle, ma per il resto?

# Vehicles ds

In [55]:
vehicles.columns

Index(['CRASH_UNIT_ID', 'RD_NO', 'CRASH_DATE', 'UNIT_NO', 'UNIT_TYPE',
       'VEHICLE_ID', 'MAKE', 'MODEL', 'LIC_PLATE_STATE', 'VEHICLE_YEAR',
       'VEHICLE_DEFECT', 'VEHICLE_TYPE', 'VEHICLE_USE', 'TRAVEL_DIRECTION',
       'MANEUVER', 'OCCUPANT_CNT', 'FIRST_CONTACT_POINT'],
      dtype='object')

UNIT_TYPE                  1           X rimosso

VEHICLE_ID             10373

MAKE                   10373

MODEL                  11786

LIC_PLATE_STATE        49629

VEHICLE_YEAR           88655

VEHICLE_DEFECT         10373

VEHICLE_TYPE           10373

VEHICLE_USE            10373

TRAVEL_DIRECTION       10373

MANEUVER               10373

OCCUPANT_CNT           10373

FIRST_CONTACT_POINT    10388

In [127]:
lic = vehicles[vehicles['LIC_PLATE_STATE'].isnull()]
ll = lic['UNIT_TYPE'].value_counts()
ll

UNIT_TYPE
DRIVER                 39144
PEDESTRIAN              6091
BICYCLE                 3761
NON-MOTOR VEHICLE        472
PARKED                    92
NON-CONTACT VEHICLE       62
DRIVERLESS                 6
Name: count, dtype: int64

In [141]:
la = vehicles[vehicles['UNIT_TYPE'] == 'NON-CONTACT VEHICLE']
la['LIC_PLATE_STATE'].value_counts()

LIC_PLATE_STATE
IL    33
XX     6
TN     1
Name: count, dtype: int64

In [131]:
a = vehicles[vehicles['LIC_PLATE_STATE'].isnull()]
a['UNIT_TYPE'].value_counts()

UNIT_TYPE
DRIVER                 39144
PEDESTRIAN              6091
BICYCLE                 3761
NON-MOTOR VEHICLE        472
PARKED                    92
NON-CONTACT VEHICLE       62
DRIVERLESS                 6
Name: count, dtype: int64

In [152]:
chicago_sky = crashes[crashes['STREET_NAME'] =='CHICAGO SKYWAY OB']
chicago_sky_with_location = chicago_sky[chicago_sky['LOCATION'].notnull()]

lat = chicago_sky_with_location['LATITUDE'].mean()
log = chicago_sky_with_location['LONGITUDE'].mean()

lat

41.74227883457143

In [153]:
log

-87.57590929792856

In [159]:
la_salle= crashes[crashes['STREET_NAME'] =='LA SALLE DR']
la_salle_loc = la_s[la_s['LOCATION'].notnull()]

la_salle_lat = la_s_loc['LATITUDE'].mean()
la_salle_log = la_s_loc['LONGITUDE'].mean()

la_s_lat

41.90103851500532

In [160]:
la_s_log

-87.63245768456915

In [120]:
vehicles[vehicles['LIC_PLATE_STATE'].isnull()]

CRASH_UNIT_ID     RD_NO              CRASH_DATE  UNIT_NO UNIT_TYPE  \
8              561513  JC113579  01/11/2019 10:45:00 PM        1    DRIVER   
12             561515  JC113568  01/11/2019 10:16:00 PM        1    DRIVER   
15             561507  JC113569  01/11/2019 10:00:00 PM        1    DRIVER   
51             561455  JC113370  01/11/2019 07:10:00 PM        1    DRIVER   
55             561409  JC113366  01/11/2019 07:06:00 PM        1    DRIVER   
...               ...       ...                     ...      ...       ...   
460377              8  HY368496  08/04/2015 10:00:00 AM        1    DRIVER   
460380              6  HY368370  08/04/2015 08:00:00 AM        1    DRIVER   
460416          13287  HY507396  05/20/2015 02:24:00 PM        1    DRIVER   
460417         146994  JA227271  04/16/2015 10:00:00 PM        1    DRIVER   
460428          12093  HY498942  11/11/2014 08:00:00 PM        1    DRIVER   

        VEHICLE_ID        MAKE       MODEL LIC_PLATE_STATE  VEHICLE_YEAR  \
8         535691.0     UNKNOWN     UNKNOWN             NaN           NaN   
12        535692.0     UNKNOWN     UNKNOWN             NaN           NaN   
15        535681.0     UNKNOWN     UNKNOWN             NaN           NaN   
51        535624.0   CHEVROLET       TAHOE             NaN           NaN   
55        535581.0     UNKNOWN     UNKNOWN             NaN           NaN   
...            ...         ...         ...             ...           ...   
460377         8.0  VOLKSWAGEN       JETTA             NaN        2008.0   
460380         6.0     PONTIAC  BONNEVILLE             NaN           NaN   
460416     12750.0     UNKNOWN     UNKNOWN             NaN           NaN   
460417    146407.0     UNKNOWN     UNKNOWN             NaN           NaN   
460428     11595.0     UNKNOWN     UNKNOWN             NaN           NaN   

       VEHICLE_DEFECT                 VEHICLE_TYPE VEHICLE_USE  \
8             UNKNOWN  SPORT UTILITY VEHICLE (SUV)  UNKNOWN/NA   
12            UNKNOWN                   UNKNOWN/NA  UNKNOWN/NA   
15            UNKNOWN                   UNKNOWN/NA  UNKNOWN/NA   
51            UNKNOWN  SPORT UTILITY VEHICLE (SUV)  UNKNOWN/NA   
55            UNKNOWN                    PASSENGER  UNKNOWN/NA   
...               ...                          ...         ...   
460377           NONE                    PASSENGER    PERSONAL   
460380        UNKNOWN                    PASSENGER  UNKNOWN/NA   
460416        UNKNOWN                   UNKNOWN/NA  UNKNOWN/NA   
460417        UNKNOWN                   UNKNOWN/NA  UNKNOWN/NA   
460428        UNKNOWN                   UNKNOWN/NA  UNKNOWN/NA   

       TRAVEL_DIRECTION            MANEUVER  OCCUPANT_CNT FIRST_CONTACT_POINT  
8                     S          UNKNOWN/NA           1.0             UNKNOWN  
12                    N          UNKNOWN/NA           1.0             UNKNOWN  
15                    E  PASSING/OVERTAKING           1.0             UNKNOWN  
51                    E      STRAIGHT AHEAD           1.0         FRONT-RIGHT  
55                    S        TURNING LEFT           1.0             UNKNOWN  
...                 ...                 ...           ...                 ...  
460377                N      CHANGING LANES           1.0         FRONT-RIGHT  
460380                N      STRAIGHT AHEAD           1.0               FRONT  
460416          UNKNOWN          UNKNOWN/NA           1.0             UNKNOWN  
460417                N      STRAIGHT AHEAD           1.0             UNKNOWN  
460428          UNKNOWN          UNKNOWN/NA           1.0             UNKNOWN  

[49629 rows x 17 columns]

In [85]:
a = vehicles[vehicles['VEHICLE_ID'].isnull()]
a['UNIT_TYPE'].value_counts()

UNIT_TYPE
PEDESTRIAN             6091
BICYCLE                3761
NON-MOTOR VEHICLE       472
NON-CONTACT VEHICLE      42
DRIVER                    6
Name: count, dtype: int64

##### Unit type

In [83]:
unittype = vehicles['CRASH_UNIT_ID']
unittype

0         561555
1         561563
2         561564
3         561540
4         561541
           ...  
460432     30751
460433     24495
460434     24496
460435    481321
460436    481322
Name: CRASH_UNIT_ID, Length: 460437, dtype: int64

In [84]:
people['PERSON_ID']

0         O561555
1         O561563
2         O561564
3         O561540
4         O561541
           ...   
564560     O30751
564561     O24495
564562     O24496
564563    O481321
564564    P108071
Name: PERSON_ID, Length: 564565, dtype: object

In [78]:
vehicles['UNIT_TYPE'].value_counts()

UNIT_TYPE
DRIVER                 444982
PEDESTRIAN               6091
PARKED                   4827
BICYCLE                  3761
NON-MOTOR VEHICLE         472
DRIVERLESS                201
NON-CONTACT VEHICLE       102
Name: count, dtype: int64

In [76]:
crashes[crashes['RD_NO']=='JB374571']

RD_NO              CRASH_DATE  POSTED_SPEED_LIMIT  \
51567  JB374571  08/01/2018 02:59:00 PM                  25   

      TRAFFIC_CONTROL_DEVICE DEVICE_CONDITION WEATHER_CONDITION  \
51567            NO CONTROLS      NO CONTROLS             CLEAR   

      LIGHTING_CONDITION FIRST_CRASH_TYPE TRAFFICWAY_TYPE           ALIGNMENT  \
51567           DAYLIGHT     PEDALCYCLIST     NOT DIVIDED  STRAIGHT AND LEVEL   

       ... INJURIES_NON_INCAPACITATING INJURIES_REPORTED_NOT_EVIDENT  \
51567  ...                         1.0                           0.0   

      INJURIES_NO_INDICATION INJURIES_UNKNOWN CRASH_HOUR CRASH_DAY_OF_WEEK  \
51567                    6.0              0.0         14                 4   

      CRASH_MONTH   LATITUDE  LONGITUDE  \
51567           8  41.940077 -87.650295   

                                       LOCATION  
51567  POINT (-87.650294867996 41.940076854718)  

[1 rows x 36 columns]

In [163]:
unitnull = people[people['RD_NO'] == 'JB374571']
unitnull['VEHICLE_ID']

PERSON_ID PERSON_TYPE     RD_NO  VEHICLE_ID              CRASH_DATE  \
113587   O445609     BICYCLE  JB374571         NaN  08/01/2018 02:59:00 PM   
113588   O445620      DRIVER  JB374571    427330.0  08/01/2018 02:59:00 PM   
113589   O445652      DRIVER  JB374571         NaN  08/01/2018 02:59:00 PM   
113590   O445653      DRIVER  JB374571         NaN  08/01/2018 02:59:00 PM   
113591   O445667      DRIVER  JB374571    427349.0  08/01/2018 02:59:00 PM   
113592   O445904      DRIVER  JB374571         NaN  08/01/2018 02:59:00 PM   
113593   P100689   PASSENGER  JB374571    427330.0  08/01/2018 02:59:00 PM   

                   CITY STATE SEX   AGE  SAFETY_EQUIPMENT AIRBAG_DEPLOYED  \
113587  HOFFMAN ESTATES    IL   M  26.0      NONE PRESENT             NaN   
113588      DES PLAINES    IL   F  59.0  SAFETY BELT USED  DID NOT DEPLOY   
113589      DES PLAINES    IL   F  59.0  SAFETY BELT USED  DID NOT DEPLOY   
113590      DES PLAINES    IL   F  59.0  SAFETY BELT USED  DID NOT DEPLOY   
113591      DES PLAINES    IL   F  59.0  SAFETY BELT USED  DID NOT DEPLOY   
113592      DES PLAINES    IL   F  59.0  SAFETY BELT USED  DID NOT DEPLOY   
113593      DES PLAINES    IL   F  22.0  SAFETY BELT USED  DID NOT DEPLOY   

       EJECTION     INJURY_CLASSIFICATION    DRIVER_ACTION DRIVER_VISION  \
113587     NONE  NONINCAPACITATING INJURY             NONE  NOT OBSCURED   
113588     NONE   NO INDICATION OF INJURY  FAILED TO YIELD  NOT OBSCURED   
113589     NONE   NO INDICATION OF INJURY  FAILED TO YIELD  NOT OBSCURED   
113590     NONE   NO INDICATION OF INJURY  FAILED TO YIELD  NOT OBSCURED   
113591     NONE   NO INDICATION OF INJURY  FAILED TO YIELD  NOT OBSCURED   
113592     NONE   NO INDICATION OF INJURY  FAILED TO YIELD  NOT OBSCURED   
113593     NONE   NO INDICATION OF INJURY              NaN           NaN   

       PHYSICAL_CONDITION        BAC_RESULT DAMAGE_CATEGORY  DAMAGE  
113587             NORMAL  TEST NOT OFFERED    $500 OR LESS     NaN  
113588             NORMAL  TEST NOT OFFERED    $500 OR LESS     NaN  
113589             NORMAL  TEST NOT OFFERED    $500 OR LESS     NaN  
113590             NORMAL  TEST NOT OFFERED    $500 OR LESS     NaN  
113591             NORMAL  TEST NOT OFFERED    $500 OR LESS     NaN  
113592             NORMAL  TEST NOT OFFERED    $500 OR LESS     NaN  
113593                NaN               NaN    $500 OR LESS     NaN

In [167]:
passe = people[people['PERSON_TYPE'] == 'PASSENGER']
passe

PERSON_ID PERSON_TYPE     RD_NO  VEHICLE_ID              CRASH_DATE  \
8        P126669   PASSENGER  JC113604    535703.0  01/11/2019 11:08:00 PM   
11       P126665   PASSENGER  JC113579    535694.0  01/11/2019 10:45:00 PM   
14       P126674   PASSENGER  JC113617    535725.0  01/11/2019 10:28:00 PM   
22       P126663   PASSENGER  JC113528    535688.0  01/11/2019 09:35:00 PM   
23       P126664   PASSENGER  JC113528    535678.0  01/11/2019 09:35:00 PM   
...          ...         ...       ...         ...                     ...   
564533       P11   PASSENGER  HY372446        59.0  07/07/2015 03:15:00 PM   
564535       P20   PASSENGER  HY372966        83.0  07/04/2015 12:15:00 AM   
564539      P887   PASSENGER  HY451313      4677.0  06/22/2015 02:30:00 PM   
564540      P888   PASSENGER  HY451313      4682.0  06/22/2015 02:30:00 PM   
564564   P108071   PASSENGER  JB442550    460661.0  01/18/2014 06:14:00 PM   

           CITY STATE SEX   AGE  SAFETY_EQUIPMENT AIRBAG_DEPLOYED EJECTION  \
8           NaN   NaN   F   NaN     USAGE UNKNOWN  DID NOT DEPLOY     NONE   
11      CHICAGO    IL   F  29.0     USAGE UNKNOWN  DID NOT DEPLOY     NONE   
14      CHICAGO    IL   F  39.0     USAGE UNKNOWN  DID NOT DEPLOY     NONE   
22      CHICAGO    IL   F  18.0  SAFETY BELT USED  DID NOT DEPLOY     NONE   
23      CHICAGO    IL   M  25.0  SAFETY BELT USED  DID NOT DEPLOY     NONE   
...         ...   ...  ..   ...               ...             ...      ...   
564533  CHICAGO    IL   F  69.0  SAFETY BELT USED  DID NOT DEPLOY     NONE   
564535  CHICAGO    IL   M  24.0  SAFETY BELT USED  DID NOT DEPLOY     NONE   
564539      NaN   NaN   M   NaN     USAGE UNKNOWN  DID NOT DEPLOY     NONE   
564540      NaN    MN   M   NaN  SAFETY BELT USED  DID NOT DEPLOY     NONE   
564564  CHICAGO    IL   M  41.0  SAFETY BELT USED  DID NOT DEPLOY     NONE   

          INJURY_CLASSIFICATION DRIVER_ACTION DRIVER_VISION  \
8       NO INDICATION OF INJURY           NaN           NaN   
11      NO INDICATION OF INJURY           NaN           NaN   
14      NO INDICATION OF INJURY           NaN           NaN   
22      NO INDICATION OF INJURY           NaN           NaN   
23      NO INDICATION OF INJURY           NaN           NaN   
...                         ...           ...           ...   
564533  NO INDICATION OF INJURY           NaN           NaN   
564535  NO INDICATION OF INJURY           NaN           NaN   
564539  NO INDICATION OF INJURY           NaN           NaN   
564540  NO INDICATION OF INJURY           NaN           NaN   
564564  NO INDICATION OF INJURY           NaN           NaN   

       PHYSICAL_CONDITION BAC_RESULT DAMAGE_CATEGORY       DAMAGE  
8                     NaN        NaN     OVER $1,500  1702.584614  
11                    NaN        NaN     OVER $1,500  7056.834554  
14                    NaN        NaN     OVER $1,500  2090.583708  
22                    NaN        NaN     OVER $1,500  4293.840357  
23                    NaN        NaN     OVER $1,500  2493.790294  
...                   ...        ...             ...          ...  
564533                NaN        NaN     OVER $1,500  2721.754111  
564535                NaN        NaN   $501 - $1,500  1408.049718  
564539                NaN        NaN     OVER $1,500  5342.445322  
564540                NaN        NaN     OVER $1,500  3809.324686  
564564                NaN        NaN     OVER $1,500  6589.530915  

[108833 rows x 19 columns]

In [169]:
people[people['RD_NO']=='JC113528']

PERSON_ID PERSON_TYPE     RD_NO  VEHICLE_ID              CRASH_DATE  \
20   O561505      DRIVER  JC113528    535678.0  01/11/2019 09:35:00 PM   
21   O561506      DRIVER  JC113528    535688.0  01/11/2019 09:35:00 PM   
22   P126663   PASSENGER  JC113528    535688.0  01/11/2019 09:35:00 PM   
23   P126664   PASSENGER  JC113528    535678.0  01/11/2019 09:35:00 PM   

       CITY STATE SEX   AGE  SAFETY_EQUIPMENT     AIRBAG_DEPLOYED EJECTION  \
20      NaN   NaN   M   NaN     USAGE UNKNOWN  DEPLOYMENT UNKNOWN     NONE   
21  OAKLAWN    IL   M  50.0  SAFETY BELT USED      DID NOT DEPLOY     NONE   
22  CHICAGO    IL   F  18.0  SAFETY BELT USED      DID NOT DEPLOY     NONE   
23  CHICAGO    IL   M  25.0  SAFETY BELT USED      DID NOT DEPLOY     NONE   

      INJURY_CLASSIFICATION DRIVER_ACTION DRIVER_VISION PHYSICAL_CONDITION  \
20  NO INDICATION OF INJURY       UNKNOWN       UNKNOWN            UNKNOWN   
21  NO INDICATION OF INJURY          NONE  NOT OBSCURED             NORMAL   
22  NO INDICATION OF INJURY           NaN           NaN                NaN   
23  NO INDICATION OF INJURY           NaN           NaN                NaN   

          BAC_RESULT DAMAGE_CATEGORY       DAMAGE  
20  TEST NOT OFFERED     OVER $1,500  3335.028867  
21  TEST NOT OFFERED     OVER $1,500  4592.998567  
22               NaN     OVER $1,500  4293.840357  
23               NaN     OVER $1,500  2493.790294

In [168]:
vehicles[vehicles['RD_NO']=='JC113528']

CRASH_UNIT_ID     RD_NO              CRASH_DATE  UNIT_NO UNIT_TYPE  \
17         561505  JC113528  01/11/2019 09:35:00 PM        1    DRIVER   
18         561506  JC113528  01/11/2019 09:35:00 PM        2    DRIVER   

    VEHICLE_ID     MAKE       MODEL LIC_PLATE_STATE  VEHICLE_YEAR  \
17    535678.0  PONTIAC  GRAND PRIX              IL        1999.0   
18    535688.0  PONTIAC          G6              IL        2006.0   

   VEHICLE_DEFECT VEHICLE_TYPE VEHICLE_USE TRAVEL_DIRECTION  \
17        UNKNOWN    PASSENGER    PERSONAL                E   
18           NONE    PASSENGER    PERSONAL                S   

                     MANEUVER  OCCUPANT_CNT FIRST_CONTACT_POINT  
17  AVOIDING VEHICLES/OBJECTS           2.0          FRONT-LEFT  
18               TURNING LEFT           2.0          SIDE-RIGHT

In [166]:
vehicles['UNIT_TYPE'].unique()

array(['DRIVER', 'PARKED', 'PEDESTRIAN', 'BICYCLE', 'NON-MOTOR VEHICLE',
       'DRIVERLESS', 'NON-CONTACT VEHICLE', nan], dtype=object)

considerando che i passeggeri coinvolti negli incidenti non sono riportati nel ds vehicles, abbiamo deciso di rimuovere la riga

vehicle

In [184]:
vehicle3 = vehicles.sort_values(by='VEHICLE_ID')
# Rimuoviamo i valori nulli
vehicles2 = vehicle3['VEHICLE_ID'].dropna()

# Controlla se i valori sono progressivi
progressive = (vehicles2.diff().fillna(0) >= 0).all()

# Mostra il risultato
if progressive:
    print("I valori nella colonna (escludendo i nulli) sono progressivi.")
else:
    print("I valori nella colonna (escludendo i nulli) NON sono progressivi.")

I valori nella colonna (escludendo i nulli) sono progressivi.


In [186]:
vehicles2

460383         2.0
460384         3.0
460382         4.0
460380         6.0
460381         7.0
            ...   
10        535723.0
11        535725.0
1         535738.0
2         535741.0
0         535742.0
Name: VEHICLE_ID, Length: 450064, dtype: float64

In [59]:
colonne = ['VEHICLE_ID', 'MAKE', 'VEHICLE_DEFECT', 'VEHICLE_TYPE', 
           'VEHICLE_USE', 'TRAVEL_DIRECTION', 'MANEUVER', 'OCCUPANT_CNT']

df_null = vehicles[colonne].isnull()

righe_con_null = df_null.all(axis=1)

righe_con_tutti_null = vehicles[righe_con_null]

righe_con_tutti_null['UNIT_TYPE'].value_counts()

UNIT_TYPE
PEDESTRIAN             6091
BICYCLE                3761
NON-MOTOR VEHICLE       472
NON-CONTACT VEHICLE      42
DRIVER                    6
Name: count, dtype: int64

##### 10373 righe hanno valori nulli per le colonne: VEHICLE_ID, MAKE, VEHICLE_DEFECT,VEHICLE_TYPE, VEHICLE_USE, TRAVEL_DIRECTION, MANEUVER, OCCUPANT_CNT perchè sono tutti pedoni/bici/senza macchina

In [104]:
vehicles['FIRST_CONTACT_POINT'].value_counts()

FIRST_CONTACT_POINT
FRONT                98284
REAR                 70325
FRONT-RIGHT          61541
FRONT-LEFT           57494
UNKNOWN              44917
SIDE-RIGHT           30397
SIDE-LEFT            26482
REAR-LEFT            25857
REAR-RIGHT           24029
NONE                  5379
OTHER                 1962
TOTAL (ALL AREAS)     1903
UNDER CARRIAGE         829
ROOF                   650
Name: count, dtype: int64

In [111]:
vv = vehicles[vehicles['UNIT_TYPE']== 'BICYCLE']
vv['FIRST_CONTACT_POINT'].value_counts()

Series([], Name: count, dtype: int64)

In [117]:
no_fcp = vehicles[vehicles['FIRST_CONTACT_POINT'].isnull()] 
no_fcp['UNIT_TYPE'].value_counts()

UNIT_TYPE
PEDESTRIAN             6091
BICYCLE                3761
NON-MOTOR VEHICLE       472
NON-CONTACT VEHICLE      55
DRIVER                    8
Name: count, dtype: int64

In [195]:
vehicles['TRAVEL_DIRECTION'].value_counts()

TRAVEL_DIRECTION
N          106758
S          103431
W           95333
E           92613
UNKNOWN     31089
SE           6063
NW           5458
SW           4738
NE           4581
Name: count, dtype: int64

In [193]:
driver = vehicles[vehicles['UNIT_TYPE'] == 'PEDESTRIAN']
driver['VEHICLE_TYPE'].value_counts()

Series([], Name: count, dtype: int64)

In [115]:
no_fcp[no_fcp['MANEUVER']== 'TURNING LEFT']

CRASH_UNIT_ID     RD_NO              CRASH_DATE  UNIT_NO  \
45241          504128  JB483067  10/20/2018 01:00:00 PM        1   
82970          457027  JB396892  08/17/2018 06:00:00 AM        1   
91902          445854  JB374667  08/01/2018 03:30:00 PM        1   
426504          39547  HZ219490  04/09/2016 01:45:00 PM        1   

                  UNIT_TYPE  VEHICLE_ID                        MAKE  \
45241   NON-CONTACT VEHICLE    481896.0  TOYOTA MOTOR COMPANY, LTD.   
82970   NON-CONTACT VEHICLE    437982.0                        FORD   
91902                DRIVER    427436.0                     UNKNOWN   
426504  NON-CONTACT VEHICLE     38224.0                     UNKNOWN   

               MODEL LIC_PLATE_STATE  VEHICLE_YEAR VEHICLE_DEFECT  \
45241        UNKNOWN              IL        2006.0        UNKNOWN   
82970   ESCAPE (SUV)              IL        2015.0           NONE   
91902        UNKNOWN              IL        2010.0        UNKNOWN   
426504       UNKNOWN             NaN           NaN        UNKNOWN   

                       VEHICLE_TYPE VEHICLE_USE TRAVEL_DIRECTION  \
45241   SPORT UTILITY VEHICLE (SUV)  UNKNOWN/NA                S   
82970                     PASSENGER    PERSONAL                N   
91902             BUS OVER 15 PASS.  SCHOOL BUS               SW   
426504  SPORT UTILITY VEHICLE (SUV)    PERSONAL                N   

            MANEUVER  OCCUPANT_CNT FIRST_CONTACT_POINT  
45241   TURNING LEFT           1.0                 NaN  
82970   TURNING LEFT           1.0                 NaN  
91902   TURNING LEFT           1.0                 NaN  
426504  TURNING LEFT           1.0                 NaN

In [116]:
no_fcp[no_fcp['MANEUVER']== 'STRAIGHT AHEAD']

CRASH_UNIT_ID     RD_NO              CRASH_DATE  UNIT_NO  \
77036          464430  JB411220  08/27/2018 05:20:00 PM        1   
210423         298723  JB106709  01/06/2018 03:05:00 PM        3   
237076         265869  JA519355  11/20/2017 04:30:00 PM        1   
356772         138972  JA133212  01/28/2017 01:35:00 PM        3   

                  UNIT_TYPE  VEHICLE_ID     MAKE     MODEL LIC_PLATE_STATE  \
77036   NON-CONTACT VEHICLE    444855.0   NISSAN  Frontier              TN   
210423  NON-CONTACT VEHICLE    289535.0  UNKNOWN   UNKNOWN             NaN   
237076  NON-CONTACT VEHICLE    258570.0  UNKNOWN   UNKNOWN             NaN   
356772  NON-CONTACT VEHICLE    138655.0    HONDA    ACCORD              IL   

        VEHICLE_YEAR VEHICLE_DEFECT VEHICLE_TYPE VEHICLE_USE TRAVEL_DIRECTION  \
77036         2002.0           NONE       PICKUP    PERSONAL                S   
210423           NaN        UNKNOWN   UNKNOWN/NA  UNKNOWN/NA                W   
237076           NaN           NONE   UNKNOWN/NA  UNKNOWN/NA                W   
356772        2008.0        UNKNOWN    PASSENGER  UNKNOWN/NA                W   

              MANEUVER  OCCUPANT_CNT FIRST_CONTACT_POINT  
77036   STRAIGHT AHEAD           1.0                 NaN  
210423  STRAIGHT AHEAD           1.0                 NaN  
237076  STRAIGHT AHEAD           1.0                 NaN  
356772  STRAIGHT AHEAD           1.0                 NaN

###### togliendo queste righe sopra, gli altri 10373 sono pedoni/bici/senza veicolo a motore

In [98]:
tur_left = vehicles[vehicles['MANEUVER'] == 'TURNING LEFT']
tur_left['FIRST_CONTACT_POINT'].value_counts()

FIRST_CONTACT_POINT
FRONT-RIGHT          6722
FRONT-LEFT           5660
FRONT                5143
SIDE-RIGHT           2471
SIDE-LEFT            2363
REAR-RIGHT           2135
REAR-LEFT            1881
UNKNOWN              1305
REAR                  776
NONE                  372
OTHER                 101
TOTAL (ALL AREAS)     101
UNDER CARRIAGE         25
ROOF                   17
Name: count, dtype: int64

In [99]:
ch_lanes = vehicles[vehicles['MANEUVER'] == 'STRAIGHT AHEAD']
ch_lanes['FIRST_CONTACT_POINT'].value_counts()

FIRST_CONTACT_POINT
FRONT                70902
FRONT-RIGHT          33085
REAR                 28073
FRONT-LEFT           27704
SIDE-RIGHT           17340
SIDE-LEFT            14205
UNKNOWN              11399
REAR-LEFT            10550
REAR-RIGHT           10223
NONE                  2681
TOTAL (ALL AREAS)     1304
OTHER                 1126
UNDER CARRIAGE         556
ROOF                   507
Name: count, dtype: int64

In [18]:
noc = vehicles[vehicles['OCCUPANT_CNT'].isnull()]
aaa = noc[noc['UNIT_TYPE']=='DRIVER']
aaa

CRASH_UNIT_ID     RD_NO              CRASH_DATE  UNIT_NO UNIT_TYPE  \
91168         447299  JB376407  08/02/2018 04:45:00 PM        2    DRIVER   
91744         445864  JB374941  08/01/2018 06:15:00 PM        1    DRIVER   
91939         445652  JB374571  08/01/2018 02:59:00 PM        1    DRIVER   
91940         445653  JB374571  08/01/2018 02:59:00 PM        1    DRIVER   
91941         445904  JB374571  08/01/2018 02:59:00 PM        1    DRIVER   
91994         445666  JB374559  08/01/2018 02:19:00 PM        1    DRIVER   

       VEHICLE_ID MAKE MODEL LIC_PLATE_STATE  VEHICLE_YEAR VEHICLE_DEFECT  \
91168         NaN  NaN   NaN             NaN           NaN            NaN   
91744         NaN  NaN   NaN             NaN           NaN            NaN   
91939         NaN  NaN   NaN             NaN           NaN            NaN   
91940         NaN  NaN   NaN             NaN           NaN            NaN   
91941         NaN  NaN   NaN             NaN           NaN            NaN   
91994         NaN  NaN   NaN             NaN           NaN            NaN   

      VEHICLE_TYPE VEHICLE_USE TRAVEL_DIRECTION MANEUVER  OCCUPANT_CNT  \
91168          NaN         NaN              NaN      NaN           NaN   
91744          NaN         NaN              NaN      NaN           NaN   
91939          NaN         NaN              NaN      NaN           NaN   
91940          NaN         NaN              NaN      NaN           NaN   
91941          NaN         NaN              NaN      NaN           NaN   
91994          NaN         NaN              NaN      NaN           NaN   

      FIRST_CONTACT_POINT  
91168                 NaN  
91744                 NaN  
91939                 NaN  
91940                 NaN  
91941                 NaN  
91994                 NaN

In [39]:
aaaaa = vehicles[vehicles['VEHICLE_TYPE'].isnull()]
aaaaa[aaaaa['UNIT_TYPE']=='DRIVER']

CRASH_UNIT_ID     RD_NO              CRASH_DATE  UNIT_NO UNIT_TYPE  \
91168         447299  JB376407  08/02/2018 04:45:00 PM        2    DRIVER   
91744         445864  JB374941  08/01/2018 06:15:00 PM        1    DRIVER   
91939         445652  JB374571  08/01/2018 02:59:00 PM        1    DRIVER   
91940         445653  JB374571  08/01/2018 02:59:00 PM        1    DRIVER   
91941         445904  JB374571  08/01/2018 02:59:00 PM        1    DRIVER   
91994         445666  JB374559  08/01/2018 02:19:00 PM        1    DRIVER   

       VEHICLE_ID MAKE MODEL LIC_PLATE_STATE  VEHICLE_YEAR VEHICLE_DEFECT  \
91168         NaN  NaN   NaN             NaN           NaN            NaN   
91744         NaN  NaN   NaN             NaN           NaN            NaN   
91939         NaN  NaN   NaN             NaN           NaN            NaN   
91940         NaN  NaN   NaN             NaN           NaN            NaN   
91941         NaN  NaN   NaN             NaN           NaN            NaN   
91994         NaN  NaN   NaN             NaN           NaN            NaN   

      VEHICLE_TYPE VEHICLE_USE TRAVEL_DIRECTION MANEUVER  OCCUPANT_CNT  \
91168          NaN         NaN              NaN      NaN           NaN   
91744          NaN         NaN              NaN      NaN           NaN   
91939          NaN         NaN              NaN      NaN           NaN   
91940          NaN         NaN              NaN      NaN           NaN   
91941          NaN         NaN              NaN      NaN           NaN   
91994          NaN         NaN              NaN      NaN           NaN   

      FIRST_CONTACT_POINT  
91168                 NaN  
91744                 NaN  
91939                 NaN  
91940                 NaN  
91941                 NaN  
91994                 NaN

In [196]:
vehicles['MANEUVER'].value_counts()

MANEUVER
STRAIGHT AHEAD                        229659
SLOW/STOP IN TRAFFIC                   42293
UNKNOWN/NA                             38514
TURNING LEFT                           29076
BACKING                                23129
TURNING RIGHT                          16902
PASSING/OVERTAKING                     12757
CHANGING LANES                         11343
OTHER                                   8184
ENTERING TRAFFIC LANE FROM PARKING      6385
PARKED                                  4711
MERGING                                 3723
STARTING IN TRAFFIC                     3330
SLOW/STOP - LEFT TURN                   2761
LEAVING TRAFFIC LANE TO PARK            2757
U-TURN                                  2711
ENTER FROM DRIVE/ALLEY                  2310
AVOIDING VEHICLES/OBJECTS               2241
SKIDDING/CONTROL LOSS                   2115
SLOW/STOP - RIGHT TURN                  1744
SLOW/STOP - LOAD/UNLOAD                 1457
NEGOTIATING A CURVE                      765
D

In [33]:
aaa = vehicles[vehicles['UNIT_TYPE']=='NON-MOTOR VEHICLE']
aaa['MANEUVER'].value_counts()

Series([], Name: count, dtype: int64)

In [100]:
ch_lanes = vehicles[vehicles['MANEUVER'] == 'CHANGING LANES']
ch_lanes['FIRST_CONTACT_POINT'].value_counts()

FIRST_CONTACT_POINT
FRONT-RIGHT          3492
FRONT-LEFT           2416
SIDE-RIGHT           1275
SIDE-LEFT             969
UNKNOWN               834
REAR-LEFT             833
REAR-RIGHT            651
FRONT                 505
REAR                  161
NONE                  122
TOTAL (ALL AREAS)      43
OTHER                  33
UNDER CARRIAGE          5
ROOF                    1
Name: count, dtype: int64

In [101]:
ch_lanes = vehicles[vehicles['MANEUVER'] == 'U-TURN']
ch_lanes['FIRST_CONTACT_POINT'].value_counts()

FIRST_CONTACT_POINT
FRONT-LEFT           687
FRONT                443
SIDE-LEFT            397
FRONT-RIGHT          389
REAR-LEFT            290
UNKNOWN              202
REAR-RIGHT           104
SIDE-RIGHT            84
REAR                  66
NONE                  26
TOTAL (ALL AREAS)     11
UNDER CARRIAGE         5
OTHER                  4
ROOF                   1
Name: count, dtype: int64

In [102]:
ch_lanes = vehicles[vehicles['MANEUVER'] == 'SLOW/STOP IN TRAFFIC']
ch_lanes['FIRST_CONTACT_POINT'].value_counts()

FIRST_CONTACT_POINT
REAR                 24409
FRONT                 5871
REAR-LEFT             3000
FRONT-LEFT            2124
REAR-RIGHT            2121
FRONT-RIGHT           1478
SIDE-LEFT             1370
SIDE-RIGHT             940
UNKNOWN                461
NONE                   304
OTHER                  123
TOTAL (ALL AREAS)       75
ROOF                     9
UNDER CARRIAGE           7
Name: count, dtype: int64

In [103]:
ch_lanes = vehicles[vehicles['MANEUVER'] == 'PARKED IN TRAFFIC LANE']
ch_lanes['FIRST_CONTACT_POINT'].value_counts()

FIRST_CONTACT_POINT
SIDE-LEFT            65
REAR-LEFT            58
FRONT-LEFT           53
FRONT                23
SIDE-RIGHT           23
REAR                 12
REAR-RIGHT           12
FRONT-RIGHT          10
UNKNOWN               9
NONE                  3
OTHER                 2
TOTAL (ALL AREAS)     1
Name: count, dtype: int64

# PEOPLE DATASET

In [7]:
people

PERSON_ID PERSON_TYPE     RD_NO  VEHICLE_ID              CRASH_DATE  \
0        O561555      DRIVER  JC113649    535742.0  01/12/2019 12:01:00 AM   
1        O561563      DRIVER  JC113627    535738.0  01/11/2019 11:36:00 PM   
2        O561564      DRIVER  JC113627    535741.0  01/11/2019 11:36:00 PM   
3        O561540      DRIVER  JC113637    535714.0  01/11/2019 11:31:00 PM   
4        O561541      DRIVER  JC113637    535718.0  01/11/2019 11:31:00 PM   
...          ...         ...       ...         ...                     ...   
564560    O30751      DRIVER  HZ164689     29701.0  02/24/2014 07:45:00 PM   
564561    O24495      DRIVER  HZ122950     23633.0  01/21/2014 07:40:00 AM   
564562    O24496      DRIVER  HZ122950     23634.0  01/21/2014 07:40:00 AM   
564563   O481321      DRIVER  JB442550    460655.0  01/18/2014 06:14:00 PM   
564564   P108071   PASSENGER  JB442550    460661.0  01/18/2014 06:14:00 PM   

           CITY STATE SEX   AGE  SAFETY_EQUIPMENT     AIRBAG_DEPLOYED  \
0           NaN   NaN   X   NaN     USAGE UNKNOWN  DEPLOYMENT UNKNOWN   
1       CHICAGO    IL   M  63.0     USAGE UNKNOWN      DID NOT DEPLOY   
2       CHICAGO    IL   M  36.0     USAGE UNKNOWN      DID NOT DEPLOY   
3           NaN   NaN   F   NaN     USAGE UNKNOWN  DEPLOYMENT UNKNOWN   
4       CHICAGO    IL   F  31.0  SAFETY BELT USED      DID NOT DEPLOY   
...         ...   ...  ..   ...               ...                 ...   
564560  CHICAGO    IL   M  33.0  SAFETY BELT USED      DID NOT DEPLOY   
564561  CHICAGO    IL   F  36.0  SAFETY BELT USED      DID NOT DEPLOY   
564562  CHICAGO    IL   F  41.0  SAFETY BELT USED     DEPLOYED, FRONT   
564563      NaN   NaN   M   NaN     USAGE UNKNOWN  DEPLOYMENT UNKNOWN   
564564  CHICAGO    IL   M  41.0  SAFETY BELT USED      DID NOT DEPLOY   

       EJECTION     INJURY_CLASSIFICATION                DRIVER_ACTION  \
0       UNKNOWN   NO INDICATION OF INJURY                      UNKNOWN   
1          NONE   NO INDICATION OF INJURY                         NONE   
2          NONE   NO INDICATION OF INJURY  DISREGARDED CONTROL DEVICES   
3          NONE   NO INDICATION OF INJURY                         NONE   
4          NONE   NO INDICATION OF INJURY                         NONE   
...         ...                       ...                          ...   
564560     NONE   NO INDICATION OF INJURY                         NONE   
564561     NONE   NO INDICATION OF INJURY              FAILED TO YIELD   
564562     NONE  NONINCAPACITATING INJURY                         NONE   
564563     NONE   NO INDICATION OF INJURY             IMPROPER PARKING   
564564     NONE   NO INDICATION OF INJURY                          NaN   

       DRIVER_VISION  PHYSICAL_CONDITION                       BAC_RESULT  \
0            UNKNOWN             UNKNOWN                 TEST NOT OFFERED   
1       NOT OBSCURED              NORMAL                 TEST NOT OFFERED   
2       NOT OBSCURED  IMPAIRED - ALCOHOL  TEST PERFORMED, RESULTS UNKNOWN   
3            UNKNOWN             UNKNOWN                 TEST NOT OFFERED   
4       NOT OBSCURED              NORMAL                 TEST NOT OFFERED   
...              ...                 ...                              ...   
564560  NOT OBSCURED              NORMAL                 TEST NOT OFFERED   
564561  NOT OBSCURED              NORMAL                 TEST NOT OFFERED   
564562  NOT OBSCURED              NORMAL                 TEST NOT OFFERED   
564563       UNKNOWN             UNKNOWN                 TEST NOT OFFERED   
564564           NaN                 NaN                              NaN   

       DAMAGE_CATEGORY       DAMAGE  
0          OVER $1,500  6069.089569  
1          OVER $1,500  6237.638447  
2          OVER $1,500  3802.304187  
3          OVER $1,500  3127.680131  
4          OVER $1,500  2225.886815  
...                ...          ...  
564560   $501 - $1,500  1436.117669  
564561     OVER $1,500  2713.810276  
564562     OVER $1,500  8248.141026  

In [112]:
people['INJURY_CLASSIFICATION'].isnull().sum()

296

In [125]:
inj_list

['JC111323',
 'JC110823',
 'JC100357',
 'JB572388',
 'JB566159',
 'JB566159',
 'JB566159',
 'JB566159',
 'JB558087',
 'JB555457',
 'JB552431',
 'JB545482',
 'JB529191',
 'JB528366',
 'JB528366',
 'JB527662',
 'JB527342',
 'JB524845',
 'JB522169',
 'JB525110',
 'JB518098',
 'JB513726',
 'JB512307',
 'JB504023',
 'JB502645',
 'JB501818',
 'JB497597',
 'JB493371',
 'JB491560',
 'JB491560',
 'JB491560',
 'JB491560',
 'JB482615',
 'JB482165',
 'JB463468',
 'JB457828',
 'JB457728',
 'JB451853',
 'JB449109',
 'JB449109',
 'JB449109',
 'JB449109',
 'JB443688',
 'JB440461',
 'JB436729',
 'JB429886',
 'JB429993',
 'JB428417',
 'JB442417',
 'JB435115',
 'JB412266',
 'JB403553',
 'JB404285',
 'JB397446',
 'JB395148',
 'JB402694',
 'JB390402',
 'JB377738',
 'JB374284',
 'JB369972',
 'JB368561',
 'JB380341',
 'JB362832',
 'JB362230',
 'JB362063',
 'JB357618',
 'JB356003',
 'JB347614',
 'JB340446',
 'JB339497',
 'JB342929',
 'JB333688',
 'JB332576',
 'JB330225',
 'JB330579',
 'JB334416',
 'JB325091',

In [127]:
# Filtra il DataFrame 'people' per le righe in cui 'RD_NO' è presente in 'inj_list'
filtered_people = people[people['RD_NO'].isin(inj_list)]

# Conta le occorrenze di ciascun ID 'RD_NO' in 'filtered_people'
id_counts = filtered_people['RD_NO'].value_counts()

# Filtra gli ID che compaiono solo una volta e trasformali in una lista
single_occurrence_ids = id_counts[id_counts == 1].index.tolist()

# Visualizza la lista degli ID che compaiono solo una volta
print(single_occurrence_ids)


['JA465313', 'JB482615', 'JB529191', 'JA244525', 'JA406455', 'HZ157296', 'HZ328446']


In [119]:
# Filtra il DataFrame 'crashes' per le righe che hanno 'RD_NO' presente in 'inj_list'
for idd in inj_list:
    # Trova le righe corrispondenti a questo 'RD_NO' specifico e stampa il valore di 'INJURY_TOTAL'
    rows = crashes.loc[crashes['RD_NO'] == idd, 'MOST_SEVERE_INJURY']
    if not rows.empty:
        print(rows.values)  # Stampa i valori di 'INJURY_TOTAL' per le righe corrispondenti


['NO INDICATION OF INJURY']
['NO INDICATION OF INJURY']
['NONINCAPACITATING INJURY']
['NO INDICATION OF INJURY']
['NO INDICATION OF INJURY']
['NO INDICATION OF INJURY']
['NO INDICATION OF INJURY']
['NO INDICATION OF INJURY']
['NO INDICATION OF INJURY']
['NO INDICATION OF INJURY']
['NO INDICATION OF INJURY']
['NO INDICATION OF INJURY']
[nan]
['NO INDICATION OF INJURY']
['NO INDICATION OF INJURY']
['NO INDICATION OF INJURY']
['NO INDICATION OF INJURY']
['NO INDICATION OF INJURY']
['NO INDICATION OF INJURY']
['NO INDICATION OF INJURY']
['NO INDICATION OF INJURY']
['NO INDICATION OF INJURY']
['NO INDICATION OF INJURY']
['NO INDICATION OF INJURY']
['NO INDICATION OF INJURY']
['NO INDICATION OF INJURY']
['NO INDICATION OF INJURY']
['NO INDICATION OF INJURY']
['NO INDICATION OF INJURY']
['NO INDICATION OF INJURY']
['NO INDICATION OF INJURY']
['NO INDICATION OF INJURY']
[nan]
['NO INDICATION OF INJURY']
['NO INDICATION OF INJURY']
['NO INDICATION OF INJURY']
['NO INDICATION OF INJURY']
['NO IN

In [107]:
people['INJURY_CLASSIFICATION'].value_counts()

INJURY_CLASSIFICATION
NO INDICATION OF INJURY     524430
NONINCAPACITATING INJURY     21334
REPORTED, NOT EVIDENT        13843
INCAPACITATING INJURY         4426
FATAL                          236
Name: count, dtype: int64

In [129]:
people['DRIVER_ACTION'].value_counts()

DRIVER_ACTION
NONE                                 171361
UNKNOWN                               97822
FAILED TO YIELD                       45427
OTHER                                 36727
FOLLOWED TOO CLOSELY                  32432
IMPROPER BACKING                      15534
IMPROPER LANE CHANGE                  13214
IMPROPER TURN                         12291
IMPROPER PASSING                      10452
TOO FAST FOR CONDITIONS                7348
DISREGARDED CONTROL DEVICES            6509
IMPROPER PARKING                       1858
WRONG WAY/SIDE                         1531
CELL PHONE USE OTHER THAN TEXTING       881
EVADING POLICE VEHICLE                  744
EMERGENCY VEHICLE ON CALL               369
TEXTING                                 222
STOPPED SCHOOL BUS                       63
LICENSE RESTRICTIONS                     14
Name: count, dtype: int64

In [162]:
dd = people[people['BAC_RESULT'].isnull()]
dd['PERSON_TYPE'].value_counts()

PERSON_TYPE
PASSENGER    108833
Name: count, dtype: int64

In [163]:
passs = people[people['PERSON_TYPE'] == 'PASSENGER']
passs['BAC_RESULT'].value_counts()

Series([], Name: count, dtype: int64)

In [106]:
people['PERSON_TYPE'].value_counts()

PERSON_TYPE
DRIVER                 444982
PASSENGER              108833
PEDESTRIAN               6352
BICYCLE                  3799
NON-MOTOR VEHICLE         496
NON-CONTACT VEHICLE       103
Name: count, dtype: int64

In [120]:
people['INJURY_CLASSIFICATION'].value_counts()

INJURY_CLASSIFICATION
NO INDICATION OF INJURY     524430
NONINCAPACITATING INJURY     21334
REPORTED, NOT EVIDENT        13843
INCAPACITATING INJURY         4426
FATAL                          236
Name: count, dtype: int64

In [123]:
crashes['MOST_SEVERE_INJURY'].value_counts()

MOST_SEVERE_INJURY
NO INDICATION OF INJURY     228475
NONINCAPACITATING INJURY     15808
REPORTED, NOT EVIDENT         9703
INCAPACITATING INJURY         3723
FATAL                          209
Name: count, dtype: int64

In [99]:
ej = people[people['EJECTION'].isnull()]
ej['PERSON_TYPE'].value_counts()

PERSON_TYPE
PEDESTRIAN             6352
NON-MOTOR VEHICLE       242
BICYCLE                  71
PASSENGER                20
NON-CONTACT VEHICLE      20
Name: count, dtype: int64

In [104]:
eje  = people[people['PERSON_TYPE'] == 'NON-MOTOR VEHICLE']
eje['EJECTION'].value_counts()

EJECTION
NONE                 236
UNKNOWN               15
TOTALLY EJECTED        2
PARTIALLY EJECTED      1
Name: count, dtype: int64

In [59]:
no_vehicle = people[people['VEHICLE_ID'].isnull()]

In [60]:
no_vehicle['PERSON_TYPE'].unique()

array(['PEDESTRIAN', 'BICYCLE', 'NON-MOTOR VEHICLE',
       'NON-CONTACT VEHICLE', 'DRIVER'], dtype=object)

In [61]:
no_v_ped = no_vehicle[no_vehicle['PERSON_TYPE'] == 'PEDESTRIAN']

In [62]:
no_v_ped = no_vehicle[no_vehicle['PERSON_TYPE'] == 'BICYCLE']

In [63]:
no_v_ped = no_vehicle[no_vehicle['PERSON_TYPE'] == 'NON-MOTOR VEHICLE']

In [65]:
no_v_noncont = no_vehicle[no_vehicle['PERSON_TYPE'] == 'NON-CONTACT VEHICLE']

In [95]:
people['VEHICLE_ID'].isnull().sum()

10696

In [84]:
aa = vehicles[vehicles['CRASH_UNIT_ID'] == 347069]
aa

CRASH_UNIT_ID     RD_NO              CRASH_DATE  UNIT_NO  \
171052         347069  JB193391  03/20/2018 05:50:00 PM        1   

                  UNIT_TYPE  VEHICLE_ID MAKE MODEL LIC_PLATE_STATE  \
171052  NON-CONTACT VEHICLE         NaN  NaN   NaN             NaN   

        VEHICLE_YEAR VEHICLE_DEFECT VEHICLE_TYPE VEHICLE_USE TRAVEL_DIRECTION  \
171052           NaN            NaN          NaN         NaN              NaN   

       MANEUVER  OCCUPANT_CNT FIRST_CONTACT_POINT  
171052      NaN           NaN                 NaN

In [166]:
cinque = people[people['DAMAGE_CATEGORY'] == '$500 OR LESS']
cinque['DAMAGE'].value_counts()

Series([], Name: count, dtype: int64)

In [169]:
dam = people[people['DAMAGE'].isnull()]
dam['DAMAGE_CATEGORY'].value_counts()

DAMAGE_CATEGORY
$500 OR LESS    74309
Name: count, dtype: int64

In [180]:
cinque = people[people['DAMAGE_CATEGORY'] == 'OVER $1,500']
cinque['DAMAGE'].max()

15536.847301130172

In [173]:
people['DAMAGE_CATEGORY'].unique()

array(['OVER $1,500', '$500 OR LESS', '$501 - $1,500'], dtype=object)

In [66]:
no_v_noncont

PERSON_ID          PERSON_TYPE     RD_NO  VEHICLE_ID  \
21919    O538784  NON-CONTACT VEHICLE  JB545482         NaN   
27683    O532855  NON-CONTACT VEHICLE  JB535046         NaN   
39539    O520830  NON-CONTACT VEHICLE  JB514012         NaN   
46294    O514021  NON-CONTACT VEHICLE  JB501818         NaN   
56736    O503649  NON-CONTACT VEHICLE  JB482165         NaN   
67068    O492712  NON-CONTACT VEHICLE  JB463468         NaN   
79342    O480289  NON-CONTACT VEHICLE  JB440461         NaN   
96672    O462919  NON-CONTACT VEHICLE  JB408384         NaN   
118090   O448833  NON-CONTACT VEHICLE  JB380341         NaN   
140867   O417796  NON-CONTACT VEHICLE  JB321344         NaN   
163042   O395805  NON-CONTACT VEHICLE  JB281096         NaN   
175108   O384013  NON-CONTACT VEHICLE  JB260182         NaN   
178474   O381628  NON-CONTACT VEHICLE  JB255807         NaN   
179482   O379659  NON-CONTACT VEHICLE  JB252292         NaN   
183622   O375642  NON-CONTACT VEHICLE  JB244952         NaN   
202162   O357104  NON-CONTACT VEHICLE  JB211847         NaN   
212162   O347069  NON-CONTACT VEHICLE  JB193391         NaN   
220305   O339397  NON-CONTACT VEHICLE  JB179268         NaN   
227520   O332277  NON-CONTACT VEHICLE  JB166468         NaN   
247151   O311828  NON-CONTACT VEHICLE  JB130530         NaN   
266939   O292640  NON-CONTACT VEHICLE  JA566812         NaN   
275233   O283654  NON-CONTACT VEHICLE  JA552149         NaN   
278306   O280814  NON-CONTACT VEHICLE  JA547497         NaN   
286032   O272934  NON-CONTACT VEHICLE  JA533437         NaN   
299171   O259828  NON-CONTACT VEHICLE  JA508711         NaN   
306330   O252471  NON-CONTACT VEHICLE  JA496235         NaN   
307650   O251225  NON-CONTACT VEHICLE  JA494185         NaN   
310144   O248670  NON-CONTACT VEHICLE  JA489303         NaN   
310145   O248670  NON-CONTACT VEHICLE  JA489303         NaN   
315904   O249256  NON-CONTACT VEHICLE  JA487945         NaN   
323279   O239888  NON-CONTACT VEHICLE  JA467702         NaN   
331158   O227699  NON-CONTACT VEHICLE  JA451437         NaN   
351454   O207428  NON-CONTACT VEHICLE  JA410394         NaN   
352503   O206331  NON-CONTACT VEHICLE  JA407879         NaN   
383609   O175753  NON-CONTACT VEHICLE  JA323501         NaN   
385019   O174397  NON-CONTACT VEHICLE  JA318880         NaN   
395832   O164903  NON-CONTACT VEHICLE  JA288495         NaN   
406308   O170925  NON-CONTACT VEHICLE  JA307159         NaN   
410021   O151572  NON-CONTACT VEHICLE  JA241341         NaN   
427046   O138499  NON-CONTACT VEHICLE  JA182370         NaN   
447700   O114032  NON-CONTACT VEHICLE  JA103121         NaN   
467059    O94910  NON-CONTACT VEHICLE  HZ505126         NaN   
477097    O86138  NON-CONTACT VEHICLE  HZ472716         NaN   

                    CRASH_DATE      CITY STATE  SEX   AGE  SAFETY_EQUIPMENT  \
21919   12/08/2018 07:21:00 PM   CHICAGO    IL  NaN   NaN     USAGE UNKNOWN   
27683   11/30/2018 05:15:00 PM       NaN   NaN  NaN   NaN      NONE PRESENT   
39539   11/13/2018 08:01:00 AM       NaN   NaN    X   NaN     USAGE UNKNOWN   
46294   11/03/2018 12:10:00 PM   CHICAGO    IL  NaN   NaN               NaN   
56736   10/19/2018 02:00:00 PM   CHCIAGO    IL    M  71.0               NaN   
67068   10/05/2018 11:14:00 AM   CHICAGO    IL    X   NaN     USAGE UNKNOWN   
79342   09/18/2018 11:39:00 AM   CHICAGO    IL  NaN   NaN               NaN   
96672   08/25/2018 01:10:00 PM       NaN   NaN  NaN   NaN     USAGE UNKNOWN   
118090  07/26/2018 06:50:00 AM       NaN   NaN  NaN   NaN               NaN   
140867  06/25/2018 01:20:00 AM       NaN   NaN  NaN   NaN               NaN   
163042  05/27/2018 03:26:00 PM   CHICAGO    IL  NaN   NaN      NONE PRESENT   
175108  05/11/2018 10:43:00 PM       NaN   NaN    X   NaN               NaN   
178474  05/07/2018 04:45:00 PM   CHICAGO    IL  NaN   NaN               NaN   
179482  05/06/2018 11:35:00 AM       NaN   NaN    X   NaN     USAGE UNKNOWN   
183622  05/01/2018 08:45:00 AM       NaN   NaN   

In [32]:
no_saf = people[people['SAFETY_EQUIPMENT'].isnull()]

In [36]:
no_saf['PERSON_TYPE'].unique()

array(['PEDESTRIAN', 'NON-MOTOR VEHICLE', 'PASSENGER', 'BICYCLE',
       'NON-CONTACT VEHICLE'], dtype=object)

In [35]:
no_saf[no_saf['PERSON_TYPE']=='PASSENGER']

PERSON_ID PERSON_TYPE     RD_NO  VEHICLE_ID              CRASH_DATE  \
16148    P122575   PASSENGER  JB555457    519710.0  12/16/2018 06:00:00 AM   
31603    P119027   PASSENGER  JB528366    505038.0  11/25/2018 12:15:00 PM   
31604    P119029   PASSENGER  JB528366    505042.0  11/25/2018 12:15:00 PM   
36851    P118597   PASSENGER  JB525110    503534.0  11/16/2018 06:00:00 PM   
37245    P117700   PASSENGER  JB518098    499741.0  11/16/2018 09:00:00 AM   
44978    P115939   PASSENGER  JB504023    492363.0  11/05/2018 12:30:00 AM   
70099    P109995   PASSENGER  JB457828    468281.0  10/01/2018 08:40:00 AM   
116645    P99061   PASSENGER  JB368561    424558.0  07/27/2018 11:30:00 PM   
122136    P97639   PASSENGER  JB357618    419320.0  07/20/2018 11:14:00 AM   
136366    P94210   PASSENGER  JB330225    405702.0  07/01/2018 04:01:00 AM   
209661    P76633   PASSENGER  JB198056    337418.0  03/24/2018 12:40:00 PM   
213626    P75813   PASSENGER  JB191679    334170.0  03/18/2018 01:20:00 PM   
223310    P73358   PASSENGER  JB173040    324548.0  03/04/2018 07:24:00 AM   
224047    P73147   PASSENGER  JB171822    323867.0  03/03/2018 04:02:00 AM   
228042    P72171   PASSENGER  JB164514    320114.0  02/25/2018 04:00:00 AM   
229344    P71849   PASSENGER  JB162390    318956.0  02/23/2018 11:12:00 AM   
236030    P70426   PASSENGER  JB150393    312498.0  02/13/2018 10:45:00 AM   
236176    P70394   PASSENGER  JB150159    312307.0  02/13/2018 07:40:00 AM   

       CITY STATE  SEX  AGE SAFETY_EQUIPMENT AIRBAG_DEPLOYED EJECTION  \
16148   NaN   NaN  NaN  NaN              NaN             NaN      NaN   
31603   NaN   NaN  NaN  NaN              NaN             NaN      NaN   
31604   NaN   NaN  NaN  NaN              NaN             NaN      NaN   
36851   NaN   NaN  NaN  NaN              NaN             NaN      NaN   
37245   NaN   NaN  NaN  NaN              NaN             NaN      NaN   
44978   NaN   NaN  NaN  NaN              NaN             NaN      NaN   
70099   NaN   NaN  NaN  NaN              NaN             NaN      NaN   
116645  NaN   NaN  NaN  NaN              NaN             NaN      NaN   
122136  NaN   NaN  NaN  NaN              NaN             NaN      NaN   
136366  NaN   NaN  NaN  NaN              NaN             NaN      NaN   
209661  NaN   NaN  NaN  NaN              NaN             NaN      NaN   
213626  NaN   NaN  NaN  NaN              NaN             NaN      NaN   
223310  NaN   NaN  NaN  NaN              NaN             NaN      NaN   
224047  NaN   NaN  NaN  NaN              NaN             NaN      NaN   
228042  NaN    IL  NaN  NaN              NaN             NaN      NaN   
229344  NaN   NaN  NaN  NaN              NaN             NaN      NaN   
236030  NaN    IL  NaN  NaN              NaN             NaN      NaN   
236176  NaN   NaN    M  NaN              NaN             NaN      NaN   

       INJURY_CLASSIFICATION DRIVER_ACTION DRIVER_VISION PHYSICAL_CONDITION  \
16148                    NaN           NaN           NaN                NaN   
31603                    NaN           NaN           NaN                NaN   
31604                    NaN           NaN           NaN                NaN   
36851                    NaN           NaN           NaN                NaN   
37245                    NaN           NaN           NaN                NaN   
44978                    NaN           NaN           NaN                NaN   
70099                    NaN           NaN           NaN                NaN   
116645                   NaN           NaN           NaN                NaN   
122136                   NaN           NaN           NaN                NaN   
136366                   NaN           NaN           NaN                NaN   
209661                   NaN           NaN           NaN                NaN   
213626                   NaN           NaN           NaN                NaN   
223310                   NaN           NaN           NaN                NaN   
224047                   NaN  

In [49]:
no_air = people[people['AIRBAG_DEPLOYED'].isnull()]
no_air['PERSON_TYPE'].value_counts()

PERSON_TYPE
PEDESTRIAN             6352
BICYCLE                3799
NON-MOTOR VEHICLE       259
NON-CONTACT VEHICLE      23
PASSENGER                19
Name: count, dtype: int64

In [56]:
no_air = people[people['EJECTION'].isnull()]
no_air['PERSON_TYPE'].value_counts()

PERSON_TYPE
PEDESTRIAN             6352
NON-MOTOR VEHICLE       242
BICYCLE                  71
PASSENGER                20
NON-CONTACT VEHICLE      20
Name: count, dtype: int64

In [62]:
no_inj = people[people['INJURY_CLASSIFICATION'].isnull()]
people['INJURY_CLASSIFICATION'].value_counts()

INJURY_CLASSIFICATION
NO INDICATION OF INJURY     524430
NONINCAPACITATING INJURY     21334
REPORTED, NOT EVIDENT        13843
INCAPACITATING INJURY         4426
FATAL                          236
Name: count, dtype: int64

In [63]:
no_air = people[people['DRIVER_ACTION'].isnull()]
no_air['PERSON_TYPE'].value_counts()

PERSON_TYPE
PASSENGER              108833
PEDESTRIAN                589
NON-MOTOR VEHICLE         240
BICYCLE                    88
NON-CONTACT VEHICLE        16
Name: count, dtype: int64

In [64]:
people['DRIVER_ACTION'].value_counts()

DRIVER_ACTION
NONE                                 171361
UNKNOWN                               97822
FAILED TO YIELD                       45427
OTHER                                 36727
FOLLOWED TOO CLOSELY                  32432
IMPROPER BACKING                      15534
IMPROPER LANE CHANGE                  13214
IMPROPER TURN                         12291
IMPROPER PASSING                      10452
TOO FAST FOR CONDITIONS                7348
DISREGARDED CONTROL DEVICES            6509
IMPROPER PARKING                       1858
WRONG WAY/SIDE                         1531
CELL PHONE USE OTHER THAN TEXTING       881
EVADING POLICE VEHICLE                  744
EMERGENCY VEHICLE ON CALL               369
TEXTING                                 222
STOPPED SCHOOL BUS                       63
LICENSE RESTRICTIONS                     14
Name: count, dtype: int64

In [73]:
p = people[people['PERSON_TYPE'] == 'DRIVER']
p['VEHICLE_ID'].value_counts()

VEHICLE_ID
535742.0    1
176399.0    1
176366.0    1
176606.0    1
176609.0    1
           ..
354314.0    1
354397.0    1
354387.0    1
354382.0    1
460655.0    1
Name: count, Length: 444976, dtype: int64

In [172]:
driv = vehicles[vehicles['UNIT_TYPE']=='DRIVER']
driv['VEHICLE_YEAR'].value_counts()

VEHICLE_YEAR
2015.0    30415
2014.0    28169
2016.0    27090
2013.0    25917
2012.0    22523
          ...  
2994.0        1
2203.0        1
2914.0        1
2402.0        1
1962.0        1
Name: count, Length: 131, dtype: int64

In [171]:
null_year = vehicles[vehicles['VEHICLE_YEAR'].isnull()]
null_year['MODEL'].value_counts()

MODEL
UNKNOWN                                   54615
CAMRY                                       927
NISSAN ALTIMA                               720
IMPALA                                      667
MALIBU (CHEVELLE)                           601
                                          ...  
HILBILT MFG. CO., BENTON, ARKANSAS            1
TURNPIKE CRUISER                              1
LABARON                                       1
RSX                                           1
AZTEC PRODUCTS, INC., MANSFIELD, TEXAS        1
Name: count, Length: 862, dtype: int64

In [11]:
cleaned_crashes = pd.read_csv('C:/Users/al797/Desktop/cleaned_crashes.csv')

In [12]:
cleaned_crashes

RD_NO              CRASH_DATE  POSTED_SPEED_LIMIT  \
0       JC113649  01/12/2019 12:01:00 AM                  30   
1       JC113627  01/11/2019 11:36:00 PM                  30   
2       JC113637  01/11/2019 11:31:00 PM                  15   
3       JC113630  01/11/2019 11:22:00 PM                  35   
4       JC113604  01/11/2019 11:08:00 PM                  30   
...          ...                     ...                 ...   
257920  HY498942  11/11/2014 08:00:00 PM                  30   
257921  HZ400518  08/20/2014 04:50:00 PM                   0   
257922  HZ164689  02/24/2014 07:45:00 PM                  30   
257923  HZ122950  01/21/2014 07:40:00 AM                  30   
257924  JB442550  01/18/2014 06:14:00 PM                  30   

       TRAFFIC_CONTROL_DEVICE      DEVICE_CONDITION WEATHER_CONDITION  \
0                 NO CONTROLS           NO CONTROLS             CLEAR   
1           STOP SIGN/FLASHER  FUNCTIONING PROPERLY             CLEAR   
2           STOP SIGN/FLASHER  FUNCTIONING PROPERLY             CLEAR   
3                 NO CONTROLS           NO CONTROLS             CLEAR   
4              TRAFFIC SIGNAL  FUNCTIONING PROPERLY             CLEAR   
...                       ...                   ...               ...   
257920            NO CONTROLS           NO CONTROLS           UNKNOWN   
257921            NO CONTROLS           NO CONTROLS             CLEAR   
257922         TRAFFIC SIGNAL  FUNCTIONING PROPERLY              RAIN   
257923                  YIELD           NO CONTROLS             CLEAR   
257924            NO CONTROLS           NO CONTROLS             CLEAR   

            LIGHTING_CONDITION              FIRST_CRASH_TYPE  \
0       DARKNESS, LIGHTED ROAD          PARKED MOTOR VEHICLE   
1       DARKNESS, LIGHTED ROAD                         ANGLE   
2                     DARKNESS  SIDESWIPE OPPOSITE DIRECTION   
3                     DARKNESS          PARKED MOTOR VEHICLE   
4       DARKNESS, LIGHTED ROAD                      REAR END   
...                        ...                           ...   
257920                 UNKNOWN          PARKED MOTOR VEHICLE   
257921                DAYLIGHT                      REAR END   
257922                DAYLIGHT                       TURNING   
257923                DAYLIGHT                         ANGLE   
257924                    DUSK          PARKED MOTOR VEHICLE   

                        TRAFFICWAY_TYPE           ALIGNMENT  ...  \
0                           NOT DIVIDED  STRAIGHT AND LEVEL  ...   
1                           NOT DIVIDED  STRAIGHT AND LEVEL  ...   
2                           NOT DIVIDED  STRAIGHT AND LEVEL  ...   
3                           NOT DIVIDED  STRAIGHT AND LEVEL  ...   
4                           NOT DIVIDED  STRAIGHT AND LEVEL  ...   
...                                 ...                 ...  ...   
257920  DIVIDED - W/MEDIAN (NOT RAISED)  STRAIGHT AND LEVEL  ...   
257921                      NOT DIVIDED  STRAIGHT AND LEVEL  ...   
257922                      NOT DIVIDED  STRAIGHT AND LEVEL  ...   
257923  DIVIDED - W/MEDIAN (NOT RAISED)  STRAIGHT AND LEVEL  ...   
257924       DIVIDED - W/MEDIAN BARRIER  STRAIGHT AND LEVEL  ...   

       INJURIES_NON_INCAPACITATING INJURIES_REPORTED_NOT_EVIDENT  \
0                              0.0                           0.0   
1                              0.0                           0.0   
2                              0.0                           0.0   
3                              0.0                           0.0   
4                              0.0                           0.0   
...                            ...                           ...   
257920                         0.0                           0.0   
257921                         0.0                           0.0   
257922                         0.0                           0.0   
257923                         1.0                           0.0   
257924                         

In [15]:
has_nulls = cleaned_crashes.isnull().any().any()
print("Il file contiene valori nulli:", has_nulls)

# Per vedere il conteggio dei null values per colonna
null_counts = cleaned_crashes.isnull().sum()
print("Conteggio dei valori nulli per colonna:\n", null_counts)

Il file contiene valori nulli: True
Conteggio dei valori nulli per colonna:
 RD_NO                               0
CRASH_DATE                          0
POSTED_SPEED_LIMIT                  0
TRAFFIC_CONTROL_DEVICE              0
DEVICE_CONDITION                    0
WEATHER_CONDITION                   0
LIGHTING_CONDITION                  0
FIRST_CRASH_TYPE                    0
TRAFFICWAY_TYPE                     0
ALIGNMENT                           0
ROADWAY_SURFACE_COND                0
ROAD_DEFECT                         0
REPORT_TYPE                      4996
CRASH_TYPE                          0
DATE_POLICE_NOTIFIED                0
PRIM_CONTRIBUTORY_CAUSE             0
SEC_CONTRIBUTORY_CAUSE              0
STREET_NO                           0
STREET_DIRECTION                    2
STREET_NAME                         1
BEAT_OF_OCCURRENCE                  4
NUM_UNITS                           0
MOST_SEVERE_INJURY                  7
INJURIES_TOTAL                      0
INJURIES_FA

In [13]:
non_contact = vehicles[vehicles['UNIT_TYPE'] == 'NON-CONTACT VEHICLE']
non_contact['VEHICLE_ID'].value_counts().sum()

60

In [15]:
non_contact = vehicles[vehicles['UNIT_TYPE'] == 'NON-CONTACT VEHICLE']
non_contact[non_contact['VEHICLE_ID'].isnull()]

CRASH_UNIT_ID     RD_NO              CRASH_DATE  UNIT_NO  \
17645          538784  JB545482  12/08/2018 07:21:00 PM        3   
22335          532855  JB535046  11/30/2018 05:15:00 PM        1   
32036          520830  JB514012  11/13/2018 08:01:00 AM        1   
37446          514021  JB501818  11/03/2018 12:10:00 PM        1   
45919          503649  JB482165  10/19/2018 02:00:00 PM        2   
54307          492712  JB463468  10/05/2018 11:14:00 AM        3   
64311          480289  JB440461  09/18/2018 11:39:00 AM        1   
78340          462919  JB408384  08/25/2018 01:10:00 PM        2   
95531          448833  JB380341  07/26/2018 06:50:00 AM        1   
113877         417796  JB321344  06/25/2018 01:20:00 AM        1   
131718         395805  JB281096  05/27/2018 03:26:00 PM        2   
141216         384013  JB260182  05/11/2018 10:43:00 PM        1   
143943         381628  JB255807  05/07/2018 04:45:00 PM        1   
144727         379659  JB252292  05/06/2018 11:35:00 AM        1   
148042         375642  JB244952  05/01/2018 08:45:00 AM        1   
163022         357104  JB211847  04/04/2018 10:23:00 PM        2   
171052         347069  JB193391  03/20/2018 05:50:00 PM        1   
177575         339397  JB179268  03/08/2018 09:30:00 PM        2   
183429         332277  JB166468  02/26/2018 05:25:00 AM        1   
199621         311828  JB130530  01/26/2018 02:30:00 PM        1   
215841         292640  JA566812  12/29/2017 02:00:00 PM        2   
222681         283654  JA552149  12/16/2017 10:25:00 PM        3   
225128         280814  JA547497  12/13/2017 07:45:00 AM        3   
231413         272934  JA533437  12/02/2017 08:58:00 AM        1   
242096         259828  JA508711  11/12/2017 06:05:00 AM        1   
248013         252471  JA496235  11/02/2017 05:00:00 PM        1   
249116         251225  JA494185  11/01/2017 09:15:00 AM        2   
251137         248670  JA489303  10/28/2017 11:28:00 AM        1   
255868         249256  JA487945  10/20/2017 04:00:00 PM        2   
261902         239888  JA467702  10/10/2017 05:00:00 PM        2   
268278         227699  JA451437  09/29/2017 01:00:00 PM        1   
284689         207428  JA410394  08/29/2017 09:48:00 AM        2   
285534         206331  JA407879  08/27/2017 06:22:00 AM        1   
310654         175753  JA323501  06/26/2017 12:00:00 PM        2   
311764         174397  JA318880  06/23/2017 06:15:00 AM        1   
320507         164903  JA288495  05/31/2017 06:00:00 AM        1   
328922         170925  JA307159  05/05/2017 06:00:00 PM        1   
331892         151572  JA241341  04/27/2017 09:20:00 AM        1   
345917         138499  JA182370  03/10/2017 04:15:00 PM        1   
363131         114032  JA103121  01/03/2017 03:40:00 PM        1   
379351          94910  HZ505126  11/06/2016 02:30:00 PM        1   
387641          86138  HZ472716  10/10/2016 02:00:00 PM        1   

                  UNIT_TYPE  VEHICLE_ID MAKE MODEL LIC_PLATE_STATE  \
17645   NON-CONTACT VEHICLE         NaN  NaN   NaN             NaN   
22335   NON-CONTACT VEHICLE         NaN  NaN   NaN             NaN   
32036   NON-CONTACT VEHICLE         NaN  NaN   NaN             NaN   
37446   NON-CONTACT VEHICLE         NaN  NaN   NaN             NaN   
45919   NON-CONTACT VEHICLE         NaN  NaN   NaN             NaN   
54307   NON-CONTACT VEHICLE         NaN  NaN   NaN             NaN   
64311   NON-CONTACT VEHICLE         NaN  NaN   NaN             NaN   
78340   NON-CONTACT VEHICLE         NaN  NaN   NaN             NaN   
95531   NON-CONTACT VEHICLE         NaN  NaN   NaN             NaN   
113877  NON-CONTACT VEHICLE         NaN  NaN   NaN             NaN   
131718  NON-CONTACT VEHICLE         NaN  NaN   NaN             NaN   
141216  NON-CONTACT VEHICLE         NaN  NaN   NaN             NaN   
143943  NON-CONTACT VEHICLE         NaN  NaN   NaN             NaN   
144727  NON-CONTACT VEHICLE         NaN  NaN   NaN             NaN   
148042  NON-CONTACT VEHICLE      

In [20]:
rd = crashes[crashes['RD_NO'] == 'JB545482']
rd

RD_NO              CRASH_DATE  POSTED_SPEED_LIMIT  \
9905  JB545482  12/08/2018 07:21:00 PM                  30   

     TRAFFIC_CONTROL_DEVICE      DEVICE_CONDITION WEATHER_CONDITION  \
9905         TRAFFIC SIGNAL  FUNCTIONING PROPERLY             CLEAR   

          LIGHTING_CONDITION          FIRST_CRASH_TYPE  \
9905  DARKNESS, LIGHTED ROAD  SIDESWIPE SAME DIRECTION   

                      TRAFFICWAY_TYPE           ALIGNMENT  ...  \
9905  DIVIDED - W/MEDIAN (NOT RAISED)  STRAIGHT AND LEVEL  ...   

     INJURIES_NON_INCAPACITATING INJURIES_REPORTED_NOT_EVIDENT  \
9905                         0.0                           0.0   

     INJURIES_NO_INDICATION INJURIES_UNKNOWN CRASH_HOUR CRASH_DAY_OF_WEEK  \
9905                    2.0              0.0         19                 7   

     CRASH_MONTH   LATITUDE  LONGITUDE  \
9905          12  41.880328 -87.749961   

                                      LOCATION  
9905  POINT (-87.749961029766 41.880327970591)  

[1 rows x 36 columns]

In [18]:
vehicles[vehicles['RD_NO'] == 'JB545482']

CRASH_UNIT_ID     RD_NO              CRASH_DATE  UNIT_NO  \
17643         538751  JB545482  12/08/2018 07:21:00 PM        1   
17644         538752  JB545482  12/08/2018 07:21:00 PM        2   
17645         538784  JB545482  12/08/2018 07:21:00 PM        3   

                 UNIT_TYPE  VEHICLE_ID  \
17643               DRIVER    514271.0   
17644               DRIVER    514279.0   
17645  NON-CONTACT VEHICLE         NaN   

                                              MAKE  \
17643  PETERBILT MOTORS CO., DIVISION PACCAR, INC.   
17644                                   OLDSMOBILE   
17645                                          NaN   

                                             MODEL LIC_PLATE_STATE  \
17643  PETERBILT MOTORS CO., DIVISION PACCAR, INC.              IL   
17644                                        Alero              IL   
17645                                          NaN             NaN   

       VEHICLE_YEAR VEHICLE_DEFECT              VEHICLE_TYPE  \
17643        2006.0           NONE  TRACTOR W/O SEMI-TRAILER   
17644        1995.0           NONE                 PASSENGER   
17645           NaN            NaN                       NaN   

                   VEHICLE_USE TRAVEL_DIRECTION                   MANEUVER  \
17643  COMMERCIAL - MULTI-UNIT                W  AVOIDING VEHICLES/OBJECTS   
17644                 PERSONAL                W      SLOW/STOP - LEFT TURN   
17645                      NaN              NaN                        NaN   

       OCCUPANT_CNT FIRST_CONTACT_POINT  
17643           1.0          FRONT-LEFT  
17644           1.0          SIDE-RIGHT  
17645           NaN                 NaN

In [31]:
people[people['RD_NO'] == 'JB501818']

PERSON_ID          PERSON_TYPE     RD_NO  VEHICLE_ID  \
46293   O514015               DRIVER  JB501818    491098.0   
46294   O514021  NON-CONTACT VEHICLE  JB501818         NaN   

                   CRASH_DATE     CITY STATE  SEX   AGE SAFETY_EQUIPMENT  \
46293  11/03/2018 12:10:00 PM  CHICAGO    IL    F  34.0    USAGE UNKNOWN   
46294  11/03/2018 12:10:00 PM  CHICAGO    IL  NaN   NaN              NaN   

      AIRBAG_DEPLOYED EJECTION    INJURY_CLASSIFICATION DRIVER_ACTION  \
46293  DID NOT DEPLOY     NONE  NO INDICATION OF INJURY       UNKNOWN   
46294             NaN      NaN                      NaN           NaN   

      DRIVER_VISION PHYSICAL_CONDITION        BAC_RESULT DAMAGE_CATEGORY  \
46293       UNKNOWN            UNKNOWN  TEST NOT OFFERED   $501 - $1,500   
46294           NaN                NaN  TEST NOT OFFERED   $501 - $1,500   

            DAMAGE  
46293  1237.659205  
46294   553.092693

In [24]:
crashdate = vehicles[['VEHICLE_ID', 'CRASH_DATE']]

VEHICLE_ID              CRASH_DATE
0         535742.0  01/12/2019 12:01:00 AM
1         535738.0  01/11/2019 11:36:00 PM
2         535741.0  01/11/2019 11:36:00 PM
3         535714.0  01/11/2019 11:31:00 PM
4         535718.0  01/11/2019 11:31:00 PM
...            ...                     ...
460432     29701.0  02/24/2014 07:45:00 PM
460433     23633.0  01/21/2014 07:40:00 AM
460434     23634.0  01/21/2014 07:40:00 AM
460435    460655.0  01/18/2014 06:14:00 PM
460436    460661.0  01/18/2014 06:14:00 PM

[460437 rows x 2 columns]

In [27]:
crashdate = vehicles[['VEHICLE_ID', 'CRASH_DATE']]

crashdate['CRASH_DATE'] = pd.to_datetime(crashdate['CRASH_DATE'])

# Ordinamento del DataFrame per la colonna 'CRASH_DATE'
df_sorted = crashdate.sort_values(by='CRASH_DATE')

C:\Users\al797\AppData\Local\Temp\ipykernel_16456\2856713983.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  crashdate['CRASH_DATE'] = pd.to_datetime(crashdate['CRASH_DATE'])
C:\Users\al797\AppData\Local\Temp\ipykernel_16456\2856713983.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  crashdate['CRASH_DATE'] = pd.to_datetime(crashdate['CRASH_DATE'])


In [38]:
df_sorted[['VEHICLE_ID', 'RD_NO']]

VEHICLE_ID     RD_NO
363446    112602.0  AJ101349
363445    112611.0  AJ101349
362987    113255.0  AJ103671
362986    113253.0  AJ103671
360666    116464.0  AJ114251
...            ...       ...
242521    253916.0  ZA510570
182640    321538.0  ZB167408
439278     25848.0  hz125235
419613     48751.0  hz273623
419612     48750.0  hz273623

[460437 rows x 2 columns]

In [36]:
df_sorted = vehicles.sort_values(by='RD_NO')